### ISSUE TITLE
[PT_BREAK] pytorch_xla_linux_bionic_py3_6_clang9_test  failing

### ISSUE THREAD

**Issue by imaginary-person** [pytorch/xla#2892] opened 2021-04-16 14:51 UTC
## 🐛 Bug

`pytorch_xla_linux_bionic_py3_6_clang9_test`  [failed](https://app.circleci.com/pipelines/github/pytorch/pytorch/303208/workflows/22fa993b-f51d-4775-9690-906a240ac16e/jobs/12490336) in PyTorch PR 56227 with this debug info:

> ### XLA failure
> Job pytorch_xla_linux_bionic_py3_6_clang9_test is failing. Please create an issue with title prefixed by [PT_BREAK] in pytorch/xla and link to to this PR. If you have questions, please reach out to @ailzhang / @dlibenzi / @JackCaoG.

## To Reproduce

https://github.com/pytorch/pytorch/pull/56227

## Expected behavior

`pytorch_xla_linux_bionic_py3_6_clang9_test` should pass

## Environment
PyTorch CI check `pytorch_xla_linux_bionic_py3_6_clang9_test`

## Additional context
This failure occurred once in four CI runs, so it wouldn't probably recur on each subsequent CI run.

**Comment by JackCaoG** [comment] 2021-04-16 17:14
Thanks @imaginary-person ! Looking at the failure message I am suspecting this is not caused by your change. Could you rerun the test and see if it will pass?

**Comment by imaginary-person** [comment] 2021-04-16 17:46
Hello @JackCaoG, thanks for taking a look!
I don't think either that the issue was caused by the changes in the PR, but I reported this issue only because the debug message stated so. It failed once with that cause in four CI runs having the same base commit of the master branch.
Nevertheless, I've triggered the CI checks again.

**Comment by imaginary-person** [comment] 2021-04-16 20:28
Hello @JackCaoG, the CI check passed this time around.

**Comment by JackCaoG** [comment] 2021-04-16 20:48
Thanks @imaginary-person for reporting! I will close this issue for now then.

**Closed by JackCaoG** 2021-04-16 20:48 UTC

**Comment by Adnios** [comment] 2021-05-22 10:52
Hello @JackCaoG . I have almost the same problem. See pr https://github.com/pytorch/pytorch/pull/58648. This may be caused by my additions of `test_mish_inplace_overlap_xla` function. Would you take a look？
