### ISSUE TITLE
Lower `torch.view_as_complex` and `torch.view_as_real` ops

### ISSUE THREAD

**Issue by wonjoo-wj** [pytorch/xla#4838] opened 2023-03-30 21:14 UTC
Lower `torch.view_as_complex` and `torch.view_as_real` ops
```
UserWarning: 0The operator aten::view_as_complex appears to be a view operator, 
but it has no implementation for the backend "xla:0". View operators don't support 
falling back to run on the CPU, since the tensor's storage cannot be shared across 
devices. (Triggered internally at /workspaces/work/pytorch/aten/src/ATen/native/CPUFallback.cpp:181.)
```

**Comment by wonjoolee95** [comment] 2023-03-30 21:21
Hmm, actually locally I can see the ops are not causing any issues:
```
>>> # torch.view_as_real
>>> torch.view_as_real(x)
tensor([[ 0.7357,  0.2793],
        [-0.4912,  0.3306],
        [ 0.3116, -0.8512],
        [-0.5027,  0.4740]])
>>> x_xla = x.to(device)
>>> torch.view_as_real(x_xla)
tensor([[ 0.7357,  0.2793],
        [-0.4912,  0.3306],
        [ 0.3116, -0.8512],
        [-0.5027,  0.4740]], device='xla:0')

>>> # torch.view_as_complex
>>> torch.view_as_complex(x)
tensor([ 0.7216-0.9419j,  1.2173+1.1527j, -0.2276+0.0402j, -0.0906-1.3466j])
>>> x_xla = x.to(device)
>>> torch.view_as_complex(x_xla)
tensor([ 0.7216-0.9419j,  1.2173+1.1527j, -0.2276+0.0402j, -0.0906-1.3466j],
       device='xla:0')
```

**Comment by wonjoolee95** [comment] 2023-04-03 21:28
I can reproduce this error on tpu-v4 with pt-2-0 release:
```
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch; import torch_xla; import torch_xla.core.xla_model as xm; device = xm.xla_device()
>>> x=torch.randn(4, 2, device=device)

>>> torch.view_as_complex(x)
<stdin>:1: UserWarning: 0The operator aten::view_as_complex appears to be a view operator, but it has no implementation for the backend "xla:1". View operators don't support falling back to run on the CPU, since the tensor's storage cannot be shared across devices. (Triggered internally at ../aten/src/ATen/native/CPUFallback.cpp:179.)
tensor([-0.5182-0.7280j, -0.7625+1.7006j, -1.1760-1.6168j, -1.0290-1.3682j],
       device='xla:1')
>>> torch_xla.__version__
'2.0'
>>> 
```

However, on nightly (as of March 30th) I can see actually this succeeds:
```
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch; import torch_xla; import torch_xla.core.xla_model as xm; device = xm.xla_device()
>>> device
device(type='xla', index=1)
>>> x=torch.randn(4, 2, device=device)
>>> x
tensor([[-0.6989, -0.0987],
        [ 0.7337, -0.9071],
        [-1.1161, -0.6090],
        [-0.4844, -0.1757]], device='xla:1')
>>> torch.view_as_complex(x)
tensor([-0.6989-0.0987j,  0.7337-0.9071j, -1.1161-0.6090j, -0.4844-0.1757j],
       device='xla:1')
>>> 
>>> torch_xla.__version__
'2.1.0'
```

**Comment by miladm** [comment] 2023-04-12 09:01
@wonjoolee95 looks like we have the needed support level. Closing this ticket. Let me know if we should reopen.

**Closed as completed by miladm** 2023-04-12 09:01 UTC
Labels: lowering

**Comment by wonjoolee95** [comment] 2023-05-12 19:37
Linking the PR that addressed this issue -- https://github.com/pytorch/xla/pull/4887.
