### ISSUE TITLE
TPU doesn't support custom backward operation

### ISSUE THREAD

**Issue by rwbfd** [pytorch/xla#2697] opened 2020-12-18 18:11 UTC
It seems that currently custom backward pass is not supported. For example, 

```
def _make_ix_like(input, dim=0):
    d = input.size(dim)
    rho = torch.arange(1, d + 1, device=input.device, dtype=input.dtype)
    view = [1] * input.dim()
    view[0] = -1
    return rho.view(view).transpose(0, dim)


class SparsemaxFunction(Function):
    """
    An implementation of sparsemax (Martins & Astudillo, 2016). See
    :cite:`DBLP:journals/corr/MartinsA16` for detailed description.
    By Ben Peters and Vlad Niculae
    """

    @staticmethod
    def forward(ctx, input, dim=-1):
        """sparsemax: normalizing sparse transform (a la softmax)

        Parameters
        ----------
        ctx : torch.autograd.function._ContextMethodMixin
        input : torch.Tensor
            any shape
        dim : int
            dimension along which to apply sparsemax

        Returns
        -------
        output : torch.Tensor
            same shape as input

        """
        ctx.dim = dim
        max_val, _ = input.max(dim=dim, keepdim=True)
        input -= max_val  # same numerical stability trick as for softmax
        tau, supp_size = SparsemaxFunction._threshold_and_support(input, dim=dim)
        output = torch.clamp(input - tau, min=0)
        ctx.save_for_backward(supp_size, output)
        return output

    @staticmethod
    def backward(ctx, grad_output):
        supp_size, output = ctx.saved_tensors
        dim = ctx.dim
        grad_input = grad_output.clone()
        grad_input[output == 0] = 0

        v_hat = grad_input.sum(dim=dim) / supp_size.to(output.dtype).squeeze()
        v_hat = v_hat.unsqueeze(dim)
        grad_input = torch.where(output != 0, grad_input - v_hat, grad_input)
        return grad_input, None

    @staticmethod
    def _threshold_and_support(input, dim=-1):
        """Sparsemax building block: compute the threshold

        Parameters
        ----------
        input: torch.Tensor
            any dimension
        dim : int
            dimension along which to apply the sparsemax

        Returns
        -------
        tau : torch.Tensor
            the threshold value
        support_size : torch.Tensor

        """

        input_srt, _ = torch.sort(input, descending=True, dim=dim)
        input_cumsum = input_srt.cumsum(dim) - 1
        rhos = _make_ix_like(input, dim)
        support = rhos * input_srt > input_cumsum

        support_size = support.sum(dim=dim).unsqueeze(dim)
        tau = input_cumsum.gather(dim, support_size - 1)
        tau /= support_size.to(input.dtype)
        return tau, support_size


sparsemax = SparsemaxFunction.apply


class Sparsemax(nn.Module):

    def __init__(self, dim=-1):
        self.dim = dim
        super(Sparsemax, self).__init__()

    def forward(self, input):
        return sparsemax(input, self.dim)
```

Will lead to freeze in TPU training.

**Comment by taylanbil** [comment] 2020-12-18 19:08
Defining custom bwd is possible, [here](https://github.com/pytorch/xla/blob/master/contrib/colab/Distributing_Large_Embedding_tables.ipynb)'s an example.

In the code snippet above, there seems to be no main function, it's just a bunch of class definitions. When I run it, it runs fine (after adding the necessary imports). Without being able to reproduce the freeze, it's difficult to help resolve the issue.

**Comment by rwbfd** [comment] 2020-12-19 02:29
Dear Taylanbil, thank you very much for the help. Here is a minimal example in Colab. 

https://colab.research.google.com/drive/1aoykO3DCPrZrVdVLoTdqZhxN56NNAdsb?usp=sharing. The issue happens in the last few lines. Please let me know if there is anything wrong. Meanwhile I will check the code you share.

**Comment by taylanbil** [comment] 2020-12-21 19:10
I'm sorry, this link does not seem minimal to me, it's a long notebook that does a bunch of stuff, like fit logistic regression from sklearn etc, but it doesn't import `torch_xla` at all. I'm not sure which cell/line to run to repro the issue. Can you give us an actual minimal repro that doesn't have anything other than torch_xla, and that I can simply run and repro the freeze?

**Comment by rwbfd** [comment] 2020-12-22 05:40
@taylanbil  I will try to make one. At the meantime, I am using PyTorch Lightning, which uses XLA in the backhand. It will be ready soon.

**Comment by rwbfd** [comment] 2020-12-22 06:20
@taylanbil This is the example. I have added where it has gone wrong. I will also post the problem for the PyTorch Lightning module.

Address: https://colab.research.google.com/gist/rwbfd/57dde430bc168505cfe7d5c42a31924e/tpu_freeze.ipynb

**Comment by taylanbil** [comment] 2020-12-22 19:10
I could not run this in colab for some reason. I copy pasted code into my GCE VM and I'm able to run. There's no freeze for me, but it crashes in validation step:
```
    output = self.evaluation_loop.evaluation_step(test_mode, batch, batch_idx, dataloader_idx)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 178, in evaluation_step
    output = self.trainer.accelerator_backend.validation_step(args)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/pytorch_lightning/accelerators/tpu_accelerator.py", line 152, in validation_step
    output = self.trainer.model.validation_step(*args)
  File "code2.py", line 315, in validation_step
    import pdb
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/pdb.py", line 76, in <module>
    import code
  File "/home/taylanbil/lightningfreeze/code.py", line 132, in <module>
    trainer.fit(training_module, train_dataloader, test_dataloader)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 468, in fit
    results = self.accelerator_backend.train()
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/pytorch_lightning/accelerators/tpu_accelerator.py", line 105, in train
    start_method=self.start_method
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 384, in spawn
    pf_cfg = _pre_fork_setup(nprocs)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 195, in _pre_fork_setup
    dev_count, dev_kind = _get_devices_per_worker()
RuntimeError: Missing TPU or GPU configuration
```

**Comment by rwbfd** [comment] 2020-12-23 07:26
@taylanbil Interesting. How long does it to compile? The compile for me takes at least 5 minutes so I quit waiting. I will try to see if GCP will help. Perhaps the reason is the XLA version? I will wait for a big longer to see what happens.

**Comment by rwbfd** [comment] 2020-12-27 01:26
@taylanbil Now that Colab has updated. I have the same issue now. Therefore, something is very fishy here. The evaluation sounds entirely innocent. I am scratching my head as to where it goes wrong.

**Comment by taylanbil** [comment] 2020-12-27 04:50
seems like something is wrong with lightning's setup. https://github.com/PyTorchLightning/pytorch-lightning/issues/5207 may be related. I would wait for a resolution of that issue.

**Comment by rwbfd** [comment] 2020-12-28 06:47
@taylanbil I think so too. Maybe we should forward this to that thread? What do you think?

**Comment by taylanbil** [comment] 2020-12-28 15:04
I already wrote the issue link here so github should have linked this issue to that, but it's up to you.

Since we don't seem to be freezing any more, I will go ahead and close this issue. Feel free to reopen if needeed.

**Closed** 2020-12-28 15:04 UTC
