### ISSUE TITLE
Error when running simple mnist demo

### ISSUE THREAD

**Issue by williamFalcon** [pytorch/xla#662] opened 2019-05-08 00:53 UTC
I made [this demo](https://github.com/williamFalcon/xla/tree/master/demo) from one of the tests, and simplified it into a standalone mnist demo. However, this error happens when it runs:

```
(tpu) waf2107@waf2107:~/pytorch/xla/demo$ python mnist.py 
2019-05-08 00:48:51.601926: I tensorflow/compiler/xla/xla_client/computation_client.cc:125] 
Loading XRT configuration from /home/waf2107/.pytorch_tpu.conf
2019-05-08 00:48:51.602163: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:3
9] XRT device CPU:0 -> /job:tpu_worker/replica:0/task:0/device:XLA_CPU:0
2019-05-08 00:48:51.602194: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:3
9] XRT device TPU:0 -> /job:tpu_worker/replica:0/task:0/device:TPU:0
2019-05-08 00:48:51.602206: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:3
9] XRT device TPU:1 -> /job:tpu_worker/replica:0/task:0/device:TPU:1
2019-05-08 00:48:51.602216: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:3
9] XRT device TPU:2 -> /job:tpu_worker/replica:0/task:0/device:TPU:2
2019-05-08 00:48:51.602223: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:3
9] XRT device TPU:3 -> /job:tpu_worker/replica:0/task:0/device:TPU:3
2019-05-08 00:48:51.602229: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:3
9] XRT device TPU:4 -> /job:tpu_worker/replica:0/task:0/device:TPU:4
2019-05-08 00:48:51.602251: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:3
9] XRT device TPU:5 -> /job:tpu_worker/replica:0/task:0/device:TPU:5
2019-05-08 00:48:51.602258: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:3
9] XRT device TPU:6 -> /job:tpu_worker/replica:0/task:0/device:TPU:6
2019-05-08 00:48:51.602264: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:3
9] XRT device TPU:7 -> /job:tpu_worker/replica:0/task:0/device:TPU:7
2019-05-08 00:48:51.602275: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:4
2] XRT default device: TPU:0
2019-05-08 00:48:51.602323: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:7
78] Initializing TPU system for worker tpu_worker:0 at grpc://10.240.1.2:8470
2019-05-08 00:48:55.209839: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:8
21] TPU topology: mesh_shape: 2
mesh_shape: 2
mesh_shape: 2
num_tasks: 1
num_tpu_devices_per_task: 8
device_coordinates: 0
device_coordinates: 0
device_coordinates: 0
device_coordinates: 0
device_coordinates: 0
device_coordinates: 1
device_coordinates: 0
device_coordinates: 1
device_coordinates: 0
device_coordinates: 0
device_coordinates: 0
device_coordinates: 1
device_coordinates: 1
device_coordinates: 1
device_coordinates: 0
device_coordinates: 0
device_coordinates: 1
device_coordinates: 0
device_coordinates: 1
device_coordinates: 1
device_coordinates: 1
device_coordinates: 0
device_coordinates: 1
device_coordinates: 1
device_coordinates: 1
2019-05-08 00:48:55.742759: E tensorflow/compiler/xla/xla_client/tf_logging.cc:11] Check fai
led: session_work.first->session()->Run( session_work.second.feed_inputs, session_work.secon
d.outputs_handles, &outputs) == ::tensorflow::Status::OK() (Not found: Op type not registere
d 'XRTAllocateFromTensor' in binary running on n-897fcadd-w-0. Make sure the Op and Kernel a
re registered in the binary running in this process. Note that if you are loading a saved gr
aph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done b
efore importing the graph, as contrib ops are lazily registered when the module is first acc
essed. vs. OK)
*** Begin stack trace ***
        tensorflow::CurrentStackTrace[abi:cxx11]()
        xla::XrtComputationClient::TransferToServer(absl::Span<xla::ComputationClient::Tenso
rSource const>)
        torch_xla::TensorToXlaData(at::Tensor const&, torch_xla::Device const&)
        torch_xla::XLATensor::GetIrValueForScalar(c10::Scalar, xla::PrimitiveType, torch_xla
::Device const&)
        torch_xla::XLATensor::GetIrValueForScalar(c10::Scalar, xla::Shape const&, torch_xla:
:Device const&)
        torch_xla::XLATensor::full(absl::Span<long long const>, c10::Scalar, torch_xla::Devi
ce const&, c10::ScalarType)
        torch_xla::AtenXlaType::full(c10::ArrayRef<long>, c10::Scalar, c10::TensorOptions co
nst&) const
        torch_xla::AtenXlaType::empty(c10::ArrayRef<long>, c10::TensorOptions const&) const
        torch::autograd::VariableType::empty(c10::ArrayRef<long>, c10::TensorOptions const&)
 const
        at::native::to(at::Tensor const&, c10::TensorOptions const&, bool, bool)
        at::TypeDefault::to(at::Tensor const&, c10::TensorOptions const&, bool, bool) const
        torch::autograd::VariableType::to(at::Tensor const&, c10::TensorOptions const&, bool
, bool) const

        _PyMethodDef_RawFastCallKeywords
        _PyMethodDescr_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_FastCallDict
        _PyObject_Call_Prepend
        _PyObject_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        PyEval_EvalCodeEx
        PyEval_EvalCode
        PyRun_FileExFlags
        PyRun_SimpleFileExFlags
        _Py_UnixMain
        __libc_start_main
*** End stack trace ***



Traceback (most recent call last):
  File "mnist.py", line 116, in <module>
    train_mnist()
  File "mnist.py", line 75, in train_mnist
    model_parallel = dp.DataParallel(MNIST, device_ids=devices)
  File "/home/waf2107/miniconda3/envs/tpu/lib/python3.7/site-packages/torch_xla-0.1-py3.7-li
nux-x86_64.egg/torch_xla_py/data_parallel.py", line 164, in __init__
    module = network().to(device=torch.device(device))
  File "/home/waf2107/miniconda3/envs/tpu/lib/python3.7/site-packages/torch/nn/modules/modul
e.py", line 386, in to
    return self._apply(convert)
  File "/home/waf2107/miniconda3/envs/tpu/lib/python3.7/site-packages/torch/nn/modules/modul
e.py", line 193, in _apply
    module._apply(fn)
  File "/home/waf2107/miniconda3/envs/tpu/lib/python3.7/site-packages/torch/nn/modules/modul
e.py", line 199, in _apply
    param.data = fn(param.data)
  File "/home/waf2107/miniconda3/envs/tpu/lib/python3.7/site-packages/torch/nn/modules/modul
e.py", line 384, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:100 : Check faile
d: session_work.first->session()->Run( session_work.second.feed_inputs, session_work.second.
outputs_handles, &outputs) == ::tensorflow::Status::OK() (Not found: Op type not registered 
'XRTAllocateFromTensor' in binary running on n-897fcadd-w-0. Make sure the Op and Kernel are
 registered in the binary running in this process. Note that if you are loading a saved grap
h which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done bef
ore importing the graph, as contrib ops are lazily registered when the module is first acces
sed. vs. OK)
*** Begin stack trace ***
        tensorflow::CurrentStackTrace[abi:cxx11]()
        xla::XrtComputationClient::TransferToServer(absl::Span<xla::ComputationClient::Tenso
RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:100 : Check failed: session_work.first->session()->Run( session_work.second.feed_inputs, session_work.second.
outputs_handles, &outputs) == ::tensorflow::Status::OK() (Not found: Op type not registered 'XRTAllocateFromTensor' in binary running on n-897fcadd-w-0. Make sure the Op and Kernel are
 registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done bef
ore importing the graph, as contrib ops are lazily registered when the module is first accessed. vs. OK)
*** Begin stack trace ***
        tensorflow::CurrentStackTrace[abi:cxx11]()
        xla::XrtComputationClient::TransferToServer(absl::Span<xla::ComputationClient::TensorSource const>)
        torch_xla::TensorToXlaData(at::Tensor const&, torch_xla::Device const&)
        torch_xla::XLATensor::GetIrValueForScalar(c10::Scalar, xla::PrimitiveType, torch_xla::Device const&)
        torch_xla::XLATensor::GetIrValueForScalar(c10::Scalar, xla::Shape const&, torch_xla::Device const&)
        torch_xla::XLATensor::full(absl::Span<long long const>, c10::Scalar, torch_xla::Device const&, c10::ScalarType)
        torch_xla::AtenXlaType::full(c10::ArrayRef<long>, c10::Scalar, c10::TensorOptions const&) const
        torch_xla::AtenXlaType::empty(c10::ArrayRef<long>, c10::TensorOptions const&) const
        torch::autograd::VariableType::empty(c10::ArrayRef<long>, c10::TensorOptions const&) const
        at::native::to(at::Tensor const&, c10::TensorOptions const&, bool, bool)
        at::TypeDefault::to(at::Tensor const&, c10::TensorOptions const&, bool, bool) const
        torch::autograd::VariableType::to(at::Tensor const&, c10::TensorOptions const&, bool, bool) const


        _PyMethodDef_RawFastCallKeywords
        _PyMethodDescr_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_FastCallDict
        _PyObject_Call_Prepend
        _PyObject_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        PyEval_EvalCodeEx
        PyEval_EvalCode
        PyRun_FileExFlags
        PyRun_SimpleFileExFlags
        _Py_UnixMain
        __libc_start_main
*** End stack trace ***
```

**Comment by dlibenzi** [comment] 2019-05-08 00:59
Unfortunately, the XRT API version you are hitting on the TPU VM, is (TF) 1.13, which does not have that API :|
1.14 should be out soon, which has that API.
Also, we are working on letting Cloud TPU customers to be able to access Nightly build (under a not supported agreement).
The latter will allow you to always be able to run against the latest bits.
Sorry about that, but we are just booting up the PyTorch/TPU project and there are a few things we need to sort out from a release POV.

**Comment by williamFalcon** [comment] 2019-05-08 01:01
oh noooo.... so close. any idea if we are talking about weeks or days for that release? NeurIPS deadline is coming up 🙈

**Comment by dlibenzi** [comment] 2019-05-08 01:56
Should be a week off or so.

**Comment by qinjian623** [comment] 2019-05-08 03:16
Here is my error:
https://github.com/pytorch/xla/issues/659#issuecomment-490329532
I think it's also caused by data transfering, but happened in a different place of source code.

Hi, @dlibenzi 
Is it the same reason?
If it is, maybe I'll also need a-week patience?

**Comment by qinjian623** [comment] 2019-05-08 04:01
I'v checked the output and confirmed it is the same error.

**Comment by dlibenzi** [comment] 2019-05-08 11:07
Yes, same reason.

**Comment by dlibenzi** [comment] 2019-05-22 19:25
Good news!
You should be able now, when you create a Cloud TPU node, to select nightly builds.
This brings the TPU VM up to the latest TPU service side.

**Comment by ailzhang** [comment] 2019-09-05 22:32
Closing issue as the nightly is available to users. Please feel free to reopen if you have followup questions. Thanks!

**Closed by ailzhang** 2019-09-05 22:32 UTC
