### ISSUE TITLE
Mismatched rank in collective ops (all-gather, reduce-scatter, and all-to-all) in PJRT runtime

### ISSUE THREAD

**Issue by ronghanghu** [pytorch/xla#3824] opened 2022-08-03 21:00 UTC
## 🐛 Bug

For the PJRT runtime, currently `xm.all_reduce` works well on v3-8 after https://github.com/pytorch/xla/pull/3704 is merged, but `xm.reduce_scatter` and `xm.all_to_all` still still do not work well, and the `xm.all_gather` under "pin_layout=False" doesn't work well (`all_gather` under "pin_layout=True" is actually [using `all_reduce`](https://github.com/pytorch/xla/blob/ff2e0ea559b5f8785c7f577834af2b5af84b6849/torch_xla/core/xla_model.py#L608-L647)).

This issue is submitted based on the discussions in https://github.com/pytorch/xla/pull/3813#issuecomment-1204215319.

## To Reproduce

The example below contains a test case for each collective op (all_gather, reduce_scatter, and all_to_all), which doesn't fully work under PJRT for now.

1. Allocate a new v3-8 TPU VM with `tpu-vm-pt-1.12` runtime and install the nightly PyTorch/XLA wheels that contain https://github.com/pytorch/xla/pull/3704
```
# torch, torchvision and torch_xla
sudo pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch-nightly+20220802-cp38-cp38-linux_x86_64.whl
sudo pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torchvision-nightly+20220802-cp38-cp38-linux_x86_64.whl
sudo pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch_xla-nightly+20220802-cp38-cp38-linux_x86_64.whl

# libtpu
sudo pip3 install https://storage.googleapis.com/cloud-tpu-tpuvm-artifacts/wheels/libtpu-nightly/libtpu_nightly-0.1.dev20220518-py3-none-any.whl
```
2. Save the following content to a file `test_pjrt_collective_ops.py`
```python3
import torch
import torch_xla.core.xla_model as xm
from torch_xla.experimental import pjrt


def test_pjrt_collective_ops():
    rank = xm.get_ordinal()
    world_size = xm.xrt_world_size()
    device = xm.xla_device()
    pin_layout = False

    xm.mark_step()

    # all-gather -- expected output for rank i on v3-8:
    #   [0, 1, 2, 3, 4, 5, 6, 7]
    t1 = (torch.ones(1) * rank).to(device)
    all_gather_out = xm.all_gather(t1, dim=0, pin_layout=pin_layout)

    # reduce-scatter -- expected output for rank i on v3-8:
    #   [-i]
    t2 = -torch.arange(world_size, dtype=torch.float32).to(device)
    reduce_scatter_out = xm.reduce_scatter(
        xm.REDUCE_SUM,
        t2,
        scale=1.0 / world_size,
        scatter_dim=0,
        shard_count=world_size,
        pin_layout=pin_layout,
    )

    # all-to-all -- expected output for rank i on v3-8:
    #   [[[-i, -i, -i, -i, -i, -i, -i, -i],
    #       0,  1,  2,  3,  4,  5,  6,  7]]]
    t3 = torch.cat(
        [
            -torch.arange(world_size, dtype=torch.float32).view(-1, 1, 1),
            torch.ones(world_size, 1, 1) * rank,
        ],
        dim=1,
    ).to(device)
    all_to_all_out = xm.all_to_all(
        t3,
        split_dimension=0,
        concat_dimension=2,
        split_count=world_size,
        pin_layout=pin_layout,
    )

    xm.mark_step()
    print(
        f"\n[rank {rank} of {world_size} (pin_layout={pin_layout})]\n"
        f"* all_gather_out:\n{all_gather_out}\n"
        f"* reduce_scatter_out:\n{reduce_scatter_out}\n"
        f"* all_to_all_out:\n{all_to_all_out}\n",
        end="",
        flush=True,
    )


if __name__ == "__main__":
    pjrt.run_multiprocess(test_pjrt_collective_ops)
```
3. Run this file under PJRT via `PJRT_DEVICE=TPU python3 test_pjrt_collective_ops.py`, which shows that these 3 collective ops have problematic outputs that do not match their rank from `xm.get_ordinal()`, printing the following
```
[rank 0 of 8 (pin_layout=False)]
* all_gather_out:
tensor([0., 1., 4., 5., 6., 7., 2., 3.], device='xla:0')
* reduce_scatter_out:
tensor([0.], device='xla:0')
* all_to_all_out:
tensor([[[0., -0., -0., -0., -0., -0., -0., -0.],
         [0., 1., 4., 5., 6., 7., 2., 3.]]], device='xla:0')

[rank 1 of 8 (pin_layout=False)]
* all_gather_out:
tensor([0., 1., 4., 5., 6., 7., 2., 3.], device='xla:1')
* reduce_scatter_out:
tensor([-1.], device='xla:1')
* all_to_all_out:
tensor([[[-1., -1., -1., -1., -1., -1., -1., -1.],
         [ 0.,  1.,  4.,  5.,  6.,  7.,  2.,  3.]]], device='xla:1')

[rank 2 of 8 (pin_layout=False)]
* all_gather_out:
tensor([0., 1., 4., 5., 6., 7., 2., 3.], device='xla:0')
* reduce_scatter_out:
tensor([-6.], device='xla:0')
* all_to_all_out:
tensor([[[-6., -6., -6., -6., -6., -6., -6., -6.],
         [ 0.,  1.,  4.,  5.,  6.,  7.,  2.,  3.]]], device='xla:0')

[rank 3 of 8 (pin_layout=False)]
* all_gather_out:
tensor([0., 1., 4., 5., 6., 7., 2., 3.], device='xla:1')
* reduce_scatter_out:
tensor([-7.], device='xla:1')
* all_to_all_out:
tensor([[[-7., -7., -7., -7., -7., -7., -7., -7.],
         [ 0.,  1.,  4.,  5.,  6.,  7.,  2.,  3.]]], device='xla:1')

[rank 4 of 8 (pin_layout=False)]
* all_gather_out:
tensor([0., 1., 4., 5., 6., 7., 2., 3.], device='xla:0')
* reduce_scatter_out:
tensor([-2.], device='xla:0')
* all_to_all_out:
tensor([[[-2., -2., -2., -2., -2., -2., -2., -2.],
         [ 0.,  1.,  4.,  5.,  6.,  7.,  2.,  3.]]], device='xla:0')

[rank 5 of 8 (pin_layout=False)]
* all_gather_out:
tensor([0., 1., 4., 5., 6., 7., 2., 3.], device='xla:1')
* reduce_scatter_out:
tensor([-3.], device='xla:1')
* all_to_all_out:
tensor([[[-3., -3., -3., -3., -3., -3., -3., -3.],
         [ 0.,  1.,  4.,  5.,  6.,  7.,  2.,  3.]]], device='xla:1')

[rank 6 of 8 (pin_layout=False)]
* all_gather_out:
tensor([0., 1., 4., 5., 6., 7., 2., 3.], device='xla:0')
* reduce_scatter_out:
tensor([-4.], device='xla:0')
* all_to_all_out:
tensor([[[-4., -4., -4., -4., -4., -4., -4., -4.],
         [ 0.,  1.,  4.,  5.,  6.,  7.,  2.,  3.]]], device='xla:0')

[rank 7 of 8 (pin_layout=False)]
* all_gather_out:
tensor([0., 1., 4., 5., 6., 7., 2., 3.], device='xla:1')
* reduce_scatter_out:
tensor([-5.], device='xla:1')
* all_to_all_out:
tensor([[[-5., -5., -5., -5., -5., -5., -5., -5.],
         [ 0.,  1.,  4.,  5.,  6.,  7.,  2.,  3.]]], device='xla:1')
```

For example, in the output above, `reduce_scatter` seems to do the "reduce" part correctly, but the "scatter" part has a rank mismatching the rank from "xm.get_ordinal".

## Expected behavior

For each rank `i` (in 0, ..., 7 on v3-8), it should have the following output:
```
all-gather -- expected output for rank i on v3-8:
   [0, 1, 2, 3, 4, 5, 6, 7]
reduce-scatter -- expected output for rank i on v3-8:
   [-i]
all-to-all -- expected output for rank i on v3-8:
   [[[-i, -i, -i, -i, -i, -i, -i, -i],
       0,  1,  2,  3,  4,  5,  6,  7]]]
```

## Environment

 - Reproducible on XLA backend [CPU/TPU]: v3-8 TPU VM with `tpu-vm-pt-1.12` runtime
 - torch_xla version: nightly 20220802 (see above)

## Additional context

* Another problem is that `xm.rendezvous` is not working under PJRT yet -- it doesn't actually introduce a barrier across all ranks. I think once these issues are resolved (and https://github.com/pytorch/xla/pull/3813 is merged), it should be possible to port most XRT codebases to PJRT.
* The `xm.all_reduce` op seems to work well under PJRT, perhaps because it's not affected by the rank order.
* The examples above use `pin_layout=False`, but they should be mostly the same if one switches to `pin_layout=True` (note that `xm.all_gather` only performs an actual all-gather under `pin_layout=False`. Under `pin_layout=True`, the API `xm.all_gather` doesn't actually perform all-gather, but instead, it [first pads the inputs with zeros and then performs all_reduce](https://github.com/pytorch/xla/blob/ff2e0ea559b5f8785c7f577834af2b5af84b6849/torch_xla/core/xla_model.py#L673-L678)). 
* Also, it would be great to tuplify the input during compilation and execution to get rid of the size limit in https://github.com/pytorch/xla/issues/3453#issuecomment-1121490148 and allow training larger models in PyTorch/XLA.

cc: @will-cromar

**Comment by will-cromar** [comment] 2022-08-18 00:44
The root cause here is twofold:

- The relationship between the TPU option `TPU_VISIBLE_DEVICES` and PjRt's `device->id()` is not deterministic, and you may get a different order on each new TPU host. This is due to an implementation detail of the TPU driver that can't easily be changed. Unfortunately, we can't know the device ID for a value of `TPU_VISIBLE_DEVICES`, until we've already initialized the TPU client in the current process.
- The [default device assignment order](https://github.com/tensorflow/tensorflow/blob/73faab182e0a0b77b63585f45409b1e91b816097/tensorflow/compiler/xla/pjrt/pjrt_client.h#L478-L481) given by PjRt is no always in order of device ID. This order determines the order of results for collectives.

We can't know the mapping between a process rank and the actual device IDs assigned to that process ahead of time. But, once the TPU client is initialized, we can use the device ID of the device assigned to each replica to set the global and local ordinals. This will make results consistent across different TPU hosts, but it may cause issues if someone relies on the process rank explicitly, e.g. if someone uses the `RANK` variable from `torchrun` or references `CLOUD_TPU_TASK_ID`.

At least by default, we should set the device assignment in order of device ID to reduce confusion.

**Comment by ronghanghu** [comment] 2022-08-18 03:32
Thanks for the explanation!

> The relationship between the TPU option TPU_VISIBLE_DEVICES and PjRt's device->id() is not deterministic
> The [default device assignment order](https://github.com/tensorflow/tensorflow/blob/73faab182e0a0b77b63585f45409b1e91b816097/tensorflow/compiler/xla/pjrt/pjrt_client.h#L478-L481) given by PjRt is no always in order of device ID.

I wonder how the current XRT runtime handles this issue? In the XRT runtime, the device rank from `xm.get_ordinal` always matches the results for collective ops. Is it possible to do/emulate something similar in the PjRt runtime?

> once the TPU client is initialized, we can use the device ID of the device assigned to each replica to set the global and local ordinals.

Yeah, this sounds great. After the TPU client is initialized, one can set up a mapping so that the user API `xm.get_ordinal` returns the assigned device for each PjRt process. In this mapping, I believe it is important that the rank returned by `xm.get_ordinal` matches the order in collective ops (reduce-scatter and all-to-all) -- especially given that the current `xm.all_gather` is by default implemented via this `xm.get_ordinal` API in https://github.com/pytorch/xla/blob/accd86afbb4accff842f66575b241a68c51fe680/torch_xla/core/xla_model.py#L635-L647 and its output needs to match other collective ops to be used together in a TPU program.

**Comment by ronghanghu** [comment] 2022-08-18 03:32
@will-cromar Thanks for the explanation!

> The relationship between the TPU option TPU_VISIBLE_DEVICES and PjRt's device->id() is not deterministic
> The [default device assignment order](https://github.com/tensorflow/tensorflow/blob/73faab182e0a0b77b63585f45409b1e91b816097/tensorflow/compiler/xla/pjrt/pjrt_client.h#L478-L481) given by PjRt is no always in order of device ID.

I wonder how the current XRT runtime handles this issue? In the XRT runtime, the device rank from `xm.get_ordinal` always matches the results for collective ops. Is it possible to do/emulate something similar in the PjRt runtime?

> once the TPU client is initialized, we can use the device ID of the device assigned to each replica to set the global and local ordinals.

Yeah, this sounds great. After the TPU client is initialized, one can set up a mapping so that the user API `xm.get_ordinal` returns the assigned device for each PjRt process. In this mapping, I believe it is important that the rank returned by `xm.get_ordinal` matches the order in collective ops (reduce-scatter and all-to-all) -- especially given that the current `xm.all_gather` is by default implemented via this `xm.get_ordinal` API in https://github.com/pytorch/xla/blob/accd86afbb4accff842f66575b241a68c51fe680/torch_xla/core/xla_model.py#L635-L647 and its output needs to match other collective ops to be used together in a TPU program.

**Comment by will-cromar** [comment] 2022-08-18 15:15
> I wonder how the current XRT runtime handles this issue? In the XRT runtime, the device rank from xm.get_ordinal always matches the results for collective ops. Is it possible to do/emulate something similar in the PjRt runtime?

Under XRT, only one process (the local XRT server) actually opens the devices, so it is guaranteed to get devices 0 - 7 (on v3-8), and can then map worker requests from replicas 0 - 7 to those devices. Under PjRt, any of the 4 process may get devices 2 and 3, for example, and the answer will be different on each TPU. You might be able to avoid the issue if you have one process per host with many threads, but my early experiments suggest that will give worse performance.

Agreed that `xm.get_ordinal` should match the rank used for collectives. I suspect that the unintuitive device assignment order given by PjRt may be a performance optimization, but the default should be the least confusing result, even if we do make device assignment configurable at some point. Otherwise, you and I won't be the only people to be stumped by this issue

**Comment by ronghanghu** [comment] 2022-08-18 16:50
@will-cromar Thanks for the follow-up! I see the differences from XRT. Agreeing that the default behavior of rank and collective ops should be the least confusing result (and as consistent to XRT from the user perspective as possible)

**Closed** 2022-08-24 22:25 UTC
