### ISSUE TITLE
[XLA:GPU] Significant memory usage increase after TF update

### ISSUE THREAD

**Issue by ymwangg** [pytorch/xla#4815] opened 2023-03-24 17:42 UTC
## 🐛 Bug

We observed significant memory increase after TF pin update on 12/20 https://github.com/pytorch/xla/pull/4324.

cc @Lokiiiiii

## To Reproduce
Use gcr docker images and [bench.py](https://gist.github.com/ymwangg/5a9fbb129d0e9cbca445096256eba815).

Prior to the TF update, the max batch size supported of bert-base-uncased is 90 and the following command works:
```
docker run --rm --runtime nvidia --gpus all --env GPU_NUM_DEVICES=1 \
-v /home/ubuntu/tmp/debug:/test gcr.io/tpu-pytorch/xla:nightly_3.7_cuda_11.2_20221220  \
bash -c "pip install transformers && python /test/bench.py --amp --batch_size 90"
```

After the TF update, the max batch size dropped to below 60 and the following command throws OOM error.
```
docker run --rm --runtime nvidia --gpus all --env GPU_NUM_DEVICES=1 \
-v /home/ubuntu/tmp/debug:/test gcr.io/tpu-pytorch/xla:nightly_3.7_cuda_11.2_20221221 \
bash -c "pip install transformers && python /test/bench.py --amp --batch_size 60"
```

After dumping the buffer-assignment.txt file, you can see the total bytes used increased significantly.
Before:
```
Total bytes used: 35913511433 (33.45GiB)
```
After:
```
Total bytes used: 58568395409 (54.55GiB)
```

## Environment

 - Reproducible on XLA backend [CPU/TPU]: GPU, Nvidia A100

**Comment by ymwangg** [comment] 2023-03-29 16:34
Ok, it looks like this is due to some [changes](https://github.com/tensorflow/tensorflow/commit/5c5eeaf0cefc40cff80072fb36735dc400d712f0) in xla gpu fusion merger that somehow reduced ops fusion.
Below is a workaround:
```diff
diff --git a/tensorflow/compiler/xla/service/gpu/fusion_merger.cc b/tensorflow/compiler/xla/service/gpu/fusion_merger.cc
index 3318b1dee23..a5310c00fd2 100644
--- a/tensorflow/compiler/xla/service/gpu/fusion_merger.cc
+++ b/tensorflow/compiler/xla/service/gpu/fusion_merger.cc
@@ -265,13 +265,13 @@ FusionDecision FusionInstructionMerger::ShouldFuse(HloInstruction* producer) {
     }
   }
 
-  GpuPerformanceModel::RunTimes t = GpuPerformanceModel::EstimateRunTimes(
-      producer, &*cost_analysis_, gpu_device_info_, producer->users(),
-      /*multi_output=*/false);
-  if (t.time_fused > t.time_unfused) {
-    ++num_fail_slower_if_fused_;
-    return "will execute slower if fused";
-  }
+  // GpuPerformanceModel::RunTimes t = GpuPerformanceModel::EstimateRunTimes(
+  //   producer, &*cost_analysis_, gpu_device_info_, producer->users(),
+  //     /*multi_output=*/false);
+  // if (t.time_fused > t.time_unfused) {
+  //   ++num_fail_slower_if_fused_;
+  //   return "will execute slower if fused";
+  // }
 
   return {};
 }
```
Will open an issue in tensorflow.

**Comment by vanbasten23** [comment] 2023-04-05 18:46
Closing this issue for now since the issue is in tensorflow. Feel free to reopen if needed.

**Closed by vanbasten23** 2023-04-05 18:46 UTC
