### ISSUE TITLE
PT-XLA 50% slowdown for R-50 relative to PT (perhaps due to BFC Allocator PR) and OOM issues

### ISSUE THREAD

**Issue by codeislife99** [pytorch/xla#3031] opened 2021-07-08 19:01 UTC
## 🐛 Bug

PT-XLA is ~50% slower for R-50 training with AMP compared to PT for a batch size of 128. For a batch size of 256 , it runs OOM whereas on PT it works just fine. 
## To Reproduce

1. Use the latest image : gcr.io/tpu-pytorch/xla:nightly_3.7_cuda_11.2 
2. Run `GPU_NUM_DEVICES=1 python3 /pytorch/xla/test/test_train_mp_imagenet_amp.py --fake_data` from [here](https://github.com/codeislife99/xla/blob/master/test/test_train_mp_imagenet_amp.py)
3. It should give an OOM error for batch size of 256 , and 50% slower for batch size of 128. 

## Expected behavior

The expected behavior is ~50% faster for batch size of 256 and ~30% for batch size of 128. https://github.com/codeislife99/xla/tree/v1.8.1_fix_xrt This tag already gives this speedup and is simply an adaptation of the changes that were made by the BFC Allocator PR creator . I suspect that since there are no benchmark tests that we run against this slipped through the cracks somehow. 

If someone can look into what caused this it would be great, since the master is equivalent to being broken right now(much slower than PT and unworkable for some hyperparameters)

**Comment by zcain117** [comment] 2021-07-08 19:07
do you see the same behavior for cuda 10.2 or cuda 10.1 ?

**Comment by codeislife99** [comment] 2021-07-08 21:37
I didn't try it yet with 10.2 or 10.1, should I do that ? Any reason you see 11.2 should deviate so much from 10.2/10.1 ?

**Comment by JackCaoG** [comment] 2021-07-08 22:03
Thanks for reporting, I will try to repo and see where the slowdown is coming from.

**Comment by byronyi** [comment] 2021-07-09 01:48
Any chance you could share the training throughput and GPU device kind?

**Comment by codeislife99** [comment] 2021-07-09 06:33
Yes the GPU device is Tesla-V100. I will edit this post with the training throughput numbers tomorrow.

**Comment by JackCaoG** [comment] 2021-07-12 22:46
I used v-100 and CUDA 11.2. In my experiment, turning on amp actually slow things now on nightly.

Without AMP I get
```
Epoch 1 train begin 21:36:41
| Training Device=xla:0/0 Epoch=1 Step=0 Loss=6.89059 Rate=6.33 GlobalRate=6.33 Time=21:37:01
| Training Device=xla:0/0 Epoch=1 Step=20 Loss=6.79297 Rate=88.64 GlobalRate=70.61 Time=21:37:19
| Training Device=xla:0/0 Epoch=1 Step=40 Loss=6.43628 Rate=285.03 GlobalRate=118.67 Time=21:37:25
| Training Device=xla:0/0 Epoch=1 Step=60 Loss=5.83108 Rate=363.68 GlobalRate=154.99 Time=21:37:31
| Training Device=xla:0/0 Epoch=1 Step=80 Loss=4.99023 Rate=394.85 GlobalRate=183.39 Time=21:37:38
| Training Device=xla:0/0 Epoch=1 Step=100 Loss=3.92699 Rate=407.49 GlobalRate=206.22 Time=21:37:44
| Training Device=xla:0/0 Epoch=1 Step=120 Loss=2.68816 Rate=412.43 GlobalRate=224.96 Time=21:37:50
| Training Device=xla:0/0 Epoch=1 Step=140 Loss=1.45841 Rate=414.88 GlobalRate=240.65 Time=21:37:56
| Training Device=xla:0/0 Epoch=1 Step=160 Loss=0.63192 Rate=415.92 GlobalRate=253.98 Time=21:38:02
| Training Device=xla:0/0 Epoch=1 Step=180 Loss=0.29340 Rate=416.22 GlobalRate=265.42 Time=21:38:08
```

With AMP I get
```
Epoch 1 train begin 22:35:20
| Training Device=xla:0/0 Epoch=1 Step=0 Loss=6.89059 Rate=4.86 GlobalRate=4.86 Time=22:35:46
| Training Device=xla:0/0 Epoch=1 Step=20 Loss=6.79297 Rate=65.45 GlobalRate=53.23 Time=22:36:10
| Training Device=xla:0/0 Epoch=1 Step=40 Loss=6.43628 Rate=254.92 GlobalRate=91.72 Time=22:36:17
| Training Device=xla:0/0 Epoch=1 Step=60 Loss=5.83108 Rate=331.52 GlobalRate=122.18 Time=22:36:24
| Training Device=xla:0/0 Epoch=1 Step=80 Loss=4.99023 Rate=362.05 GlobalRate=146.85 Time=22:36:30
| Training Device=xla:0/0 Epoch=1 Step=100 Loss=3.92699 Rate=374.24 GlobalRate=167.25 Time=22:36:37
| Training Device=xla:0/0 Epoch=1 Step=120 Loss=2.68816 Rate=379.04 GlobalRate=184.39 Time=22:36:44
| Training Device=xla:0/0 Epoch=1 Step=140 Loss=1.45841 Rate=380.75 GlobalRate=198.99 Time=22:36:50
| Training Device=xla:0/0 Epoch=1 Step=160 Loss=0.63192 Rate=381.63 GlobalRate=211.59 Time=22:36:57
| Training Device=xla:0/0 Epoch=1 Step=180 Loss=0.29340 Rate=382.19 GlobalRate=222.58 Time=22:37:04
```

I think this is aligned with what @rwightman reported a while back. Trying to figure out what is happening here..

**Comment by codeislife99** [comment] 2021-07-12 22:55
With a batch size of 256 with AMP,  I get 1145 instead of 382.19

**Comment by JackCaoG** [comment] 2021-07-12 22:59
@codeislife99 Can you post the speed for all configs(batch size, cuda version, with/without amp) you have? I will try to repo on my end too.

**Comment by JackCaoG** [comment] 2021-07-13 01:06
Seems like my workload is cpu bounded, I was using 32 core cpu, let me switch to 1 96 core one

**Comment by JackCaoG** [comment] 2021-07-13 18:04
I don't think bfc allocator pr is one to be blame with, I revert that [commit](https://github.com/tensorflow/tensorflow/commit/03cb2b9d8393d2c841c7387ad279dfc3280e5fc1) locally, rebuild pt/xla and rerun the model.

Without AMP I got
```
| Training Device=xla:0/0 Epoch=1 Step=0 Loss=6.89059 Rate=5.89 GlobalRate=5.89 Time=17:58:46
| Training Device=xla:0/0 Epoch=1 Step=20 Loss=6.79297 Rate=66.89 GlobalRate=59.04 Time=17:59:10
| Training Device=xla:0/0 Epoch=1 Step=40 Loss=6.43628 Rate=154.48 GlobalRate=91.19 Time=17:59:22
| Training Device=xla:0/0 Epoch=1 Step=60 Loss=5.83108 Rate=189.38 GlobalRate=112.20 Time=17:59:34
| Training Device=xla:0/0 Epoch=1 Step=80 Loss=4.99023 Rate=203.14 GlobalRate=126.98 Time=17:59:46
| Training Device=xla:0/0 Epoch=1 Step=100 Loss=3.92699 Rate=208.84 GlobalRate=137.99 Time=17:59:58
| Training Device=xla:0/0 Epoch=1 Step=120 Loss=2.68816 Rate=211.11 GlobalRate=146.49 Time=18:00:10
| Training Device=xla:0/0 Epoch=1 Step=140 Loss=1.45841 Rate=211.84 GlobalRate=153.23 Time=18:00:22
| Training Device=xla:0/0 Epoch=1 Step=160 Loss=0.63192 Rate=212.18 GlobalRate=158.72 Time=18:00:34
| Training Device=xla:0/0 Epoch=1 Step=180 Loss=0.29340 Rate=212.22 GlobalRate=163.27 Time=18:00:46
| Training Device=xla:0/0 Epoch=1 Step=200 Loss=0.17073 Rate=212.30 GlobalRate=167.11 Time=18:00:58
| Training Device=xla:0/0 Epoch=1 Step=220 Loss=0.11656 Rate=212.38 GlobalRate=170.40 Time=18:01:10
| Training Device=xla:0/0 Epoch=1 Step=240 Loss=0.08700 Rate=212.24 GlobalRate=173.23 Time=18:01:23
```

With AMP I got
```
| Training Device=xla:0/0 Epoch=1 Step=0 Loss=6.89059 Rate=4.61 GlobalRate=4.61 Time=17:55:53
| Training Device=xla:0/0 Epoch=1 Step=20 Loss=6.79297 Rate=54.56 GlobalRate=47.23 Time=17:56:22
| Training Device=xla:0/0 Epoch=1 Step=40 Loss=6.43628 Rate=149.67 GlobalRate=76.13 Time=17:56:34
| Training Device=xla:0/0 Epoch=1 Step=60 Loss=5.83108 Rate=187.56 GlobalRate=96.44 Time=17:56:46
| Training Device=xla:0/0 Epoch=1 Step=80 Loss=4.99023 Rate=202.60 GlobalRate=111.48 Time=17:56:58
| Training Device=xla:0/0 Epoch=1 Step=100 Loss=3.92699 Rate=209.13 GlobalRate=123.13 Time=17:57:10
| Training Device=xla:0/0 Epoch=1 Step=120 Loss=2.68816 Rate=211.68 GlobalRate=132.39 Time=17:57:22
| Training Device=xla:0/0 Epoch=1 Step=140 Loss=1.45841 Rate=212.58 GlobalRate=139.91 Time=17:57:34
| Training Device=xla:0/0 Epoch=1 Step=160 Loss=0.63192 Rate=213.08 GlobalRate=146.16 Time=17:57:46
| Training Device=xla:0/0 Epoch=1 Step=180 Loss=0.29340 Rate=213.03 GlobalRate=151.41 Time=17:57:58
```

The speed was about half as slow comparing to use bfc allocator.

**Comment by rwightman** [comment] 2021-07-13 18:15
@JackCaoG yeah, similar to what I've seen with the recent cuda nightlies, float32 was a bit faster than AMP, but I also have stream/sync crashes and other issues on the most recent 10.2 and 11.2 containers. A noteable speed drop for both AMP and float32 existed prior to those other issues (for me at least). I'm running my own training code though so may stress things a little differently

**Comment by codeislife99** [comment] 2021-07-13 20:44
This means that it might be related to switching to CUDA 11.2. All of my following measurements are on CUDA 10.2 : 

  | Batch Size | PT (Native)samples/sec | PT (XLA)samples/sec | Speedup w/ XLA
-- | -- | -- | -- | --
ResNet-50 | 256 | 770 | 1145 | 1.49
ResNet-50 | 128 | 750 | 940 | 1.25

**Comment by JackCaoG** [comment] 2021-07-14 20:58
I am able to repo the number reported above(1200 sample/sec)  using 04/16 nightly (cuda 10.2) + bfc allocator [patch](https://github.com/tensorflow/tensorflow/commit/03cb2b9d8393d2c841c7387ad279dfc3280e5fc1) 

So bfc allocator is not the source of the slowness, I will try to spend a bit more time in metric to understand what has changed bettwen mid April to know.

**Comment by codeislife99** [comment] 2021-07-15 19:40
Actually I am getting the same problem even in the CUDA 10.2 containers. These are the results for the gcr.io/tpu-pytorch/xla:nightly_3.7_cuda_10.2 containers. 

  | Batch Size | PT (Native)samples/sec | PT (XLA)samples/sec | Speedup w/ XLA
-- | -- | -- | -- | --
ResNet-50 | 256 | 770 | OOM | N/A
ResNet-50 | 128 | 750 | 375 | 0.5

**Comment by codeislife99** [comment] 2021-07-15 19:40
So I think its not a CUDA version issue but some other PR between the BFC allocator patch and the current master is causing this large slowdown.

**Comment by JackCaoG** [comment] 2021-07-15 19:43
It is a pt/xla problem, I dump the graph of amp runs of nightly and it is not reallying converting f32 to f16.  I will fix it and add more tests.

**Comment by rwightman** [comment] 2021-07-15 20:03
@JackCaoG I'm not sure if it's possible for my other issue to be related to whatever changes caused the f32/f16 regression, but here is a bit of context for my other problem that popped up on CUDA nightlies and didn't used to exist for CUDA and has never been a problem on TPU.

Below is some pseudo-ish code for an eval loop that involves a model and tracking loss/accuracy stats on device tensors (accumulating/averaging, etc). Model and stats tensors are on the same device. There is some sort of race happening, and there is sometimes a crash like the one below. float32 or amp. I can move this to another issue if you think it's completely unrelated...

```
for x, target in loader:
  out = model(input)
  loss = loss_fn(out, target)
  
  mark_step()  # moved to here, reduced likelyhood of race but didn't solve
  
  # calling .item() on one of the related tensors here will fix the race

  stats.update(out, loss)  # <- values of out and loss are NOT stable here on recent CUDA nightlies
  
  # mark_step()   # used to be here

  if step % log_interval == 0:
    call .item() on stats, log things, etc
```
   
```
Eval: [0/97 (  0%)] Loss: 6.52204 Top1: 2.7344 Top5: 18.1641
Eval: [10/97 ( 10%)] Loss: 6.82135 Top1: 0.3906 Top5: 2.7521
Eval: [20/97 ( 21%)] Loss: 6.86505 Top1: 0.3162 Top5: 1.9531
Eval: [30/97 ( 31%)] Loss: 6.87716 Top1: 0.2268 Top5: 1.4554
Eval: [40/97 ( 41%)] Loss: nan Top1: 0.2096 Top5: 1.3196
Eval: [50/97 ( 52%)] Loss: nan Top1: 0.1723 Top5: 1.1412
Eval: [60/97 ( 62%)] Loss: nan Top1: 0.1569 Top5: 1.0598
Eval: [70/97 ( 72%)] Loss: nan Top1: 0.1816 Top5: 1.0563
Eval: [80/97 ( 82%)] Loss: nan Top1: 0.1736 Top5: 1.0055
2021-07-02 01:16:25.084593: E     389 tensorflow/stream_executor/cuda/cuda_driver.cc:1175] failed to enqueue async memcpy from host to device: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered; GPU dst: 0x7f5b61b00f00; host src: 0x7f5ab229c080; size: 38535168=0x24c0000
2021-07-02 01:16:25.084741: W     374 tensorflow/stream_executor/stream.cc:275] Error blocking host until done in stream destructor: Internal: stream did not block host until done; was already in an error state
2021-07-02 01:16:25.084771: W     378 tensorflow/stream_executor/stream.cc:275] Error blocking host until done in stream destructor: Internal: stream did not block host until done; was already in an error state
2021-07-02 01:16:25.084797: W     382 tensorflow/stream_executor/stream.cc:275] Error blocking host until done in stream destructor: Internal: stream did not block host until done; was already in an error state
2021-07-02 01:16:25.084826: W     381 tensorflow/stream_executor/stream.cc:275] Error blocking host until done in stream destructor: Internal: stream did not block host until done; was already in an error state
2021-07-02 01:16:25.084860: E     383 tensorflow/stream_executor/cuda/cuda_driver.cc:1175] failed to enqueue async memcpy from host to device: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered; GPU dst: 0x7f5b63fc0f00; host src: 0x7f5aafddb080; size: 38535168=0x24c0000
2021-07-02 01:16:25.084897: W   30603 tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at xrt_execute_op.cc:432 : Internal: Could not synchronize CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.084933: W     389 tensorflow/stream_executor/stream.cc:275] Error blocking host until done in stream destructor: Internal: stream did not block host until done; was already in an error state
2021-07-02 01:16:25.084954: E     374 tensorflow/stream_executor/cuda/cuda_driver.cc:1066] stream in bad state on status query: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.085003: E     378 tensorflow/stream_executor/cuda/cuda_driver.cc:1066] stream in bad state on status query: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.085023: E     378 tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:702] Deallocating stream with pending work
2021-07-02 01:16:25.085036: E     382 tensorflow/stream_executor/cuda/cuda_driver.cc:1066] stream in bad state on status query: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.085061: E     382 tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:702] Deallocating stream with pending work
2021-07-02 01:16:25.085072: E     382 tensorflow/stream_executor/gpu/gpu_stream.cc:40] Error destroying CUDA event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.085092: E     382 tensorflow/stream_executor/cuda/cuda_driver.cc:711] failed to destroy CUDA stream for context 0x55d6810a85d0: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.085100: E     381 tensorflow/stream_executor/cuda/cuda_driver.cc:1066] stream in bad state on status query: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.085131: W     383 tensorflow/stream_executor/stream.cc:275] Error blocking host until done in stream destructor: Internal: stream did not block host until done; was already in an error state
2021-07-02 01:16:25.085156: E     389 tensorflow/stream_executor/cuda/cuda_driver.cc:1066] stream in bad state on status query: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.085173: E     389 tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:702] Deallocating stream with pending work
2021-07-02 01:16:25.085183: E     389 tensorflow/stream_executor/gpu/gpu_stream.cc:40] Error destroying CUDA event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.085200: E     374 tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:702] Deallocating stream with pending work
2021-07-02 01:16:25.085224: E     374 tensorflow/stream_executor/gpu/gpu_stream.cc:40] Error destroying CUDA event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.085231: E     378 tensorflow/stream_executor/gpu/gpu_stream.cc:40] Error destroying CUDA event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.085249: W     382 tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at xrt_state_ops.h:350 : Internal: Could not synchronize CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.085274: E     381 tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:702] Deallocating stream with pending work
2021-07-02 01:16:25.085293: E     383 tensorflow/stream_executor/cuda/cuda_driver.cc:1066] stream in bad state on status query: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.085325: E     383 tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:702] Deallocating stream with pending work
2021-07-02 01:16:25.085338: E     383 tensorflow/stream_executor/gpu/gpu_stream.cc:40] Error destroying CUDA event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.085346: E     389 tensorflow/stream_executor/cuda/cuda_driver.cc:711] failed to destroy CUDA stream for context 0x55d6810a85d0: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.085365: E     374 tensorflow/stream_executor/cuda/cuda_driver.cc:711] failed to destroy CUDA stream for context 0x55d6810a85d0: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.085386: E     378 tensorflow/stream_executor/cuda/cuda_driver.cc:711] failed to destroy CUDA stream for context 0x55d6810a85d0: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.085401: W     374 tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at xrt_state_ops.h:350 : Internal: Could not synchronize CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.085418: W     378 tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at xrt_state_ops.h:350 : Internal: Could not synchronize CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.085432: E     381 tensorflow/stream_executor/gpu/gpu_stream.cc:40] Error destroying CUDA event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.085451: E     381 tensorflow/stream_executor/cuda/cuda_driver.cc:711] failed to destroy CUDA stream for context 0x55d6810a85d0: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.085465: E     383 tensorflow/stream_executor/cuda/cuda_driver.cc:711] failed to destroy CUDA stream for context 0x55d6810a85d0: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.085488: W     389 tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at xrt_state_ops.h:350 : Internal: stream did not block host until done; was already in an error state
2021-07-02 01:16:25.085501: W     383 tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at xrt_state_ops.h:350 : Internal: stream did not block host until done; was already in an error state
2021-07-02 01:16:25.085526: W     381 tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at xrt_state_ops.h:350 : Internal: Could not synchronize CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.094826: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88] StackTrace:
2021-07-02 01:16:25.094859: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88] *** Begin stack trace ***
2021-07-02 01:16:25.094867: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 	xla::util::ReportComputationError(tensorflow::Status const&, absl::lts_20210324::Span<xla::XlaComputation const* const>, absl::lts_20210324::Span<xla::Shape const* const>)
2021-07-02 01:16:25.094873: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 	xla::XrtComputationClient::ExecuteComputation(xla::ComputationClient::Computation const&, absl::lts_20210324::Span<std::shared_ptr<xla::ComputationClient::Data> const>, std::string const&, xla::ComputationClient::ExecuteComputationOptions const&)
2021-07-02 01:16:25.094879: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88]
2021-07-02 01:16:25.094884: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 	xla::util::MultiWait::Complete(std::function<void ()> const&)
2021-07-02 01:16:25.094888: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88]
2021-07-02 01:16:25.094893: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88]
2021-07-02 01:16:25.094898: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88]
2021-07-02 01:16:25.094905: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 	clone
2021-07-02 01:16:25.094910: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88] *** End stack trace ***
2021-07-02 01:16:25.094915: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88]
2021-07-02 01:16:25.094920: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88] Status: Internal: From /job:localservice/replica:0/task:0:
2021-07-02 01:16:25.094924: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 2 root error(s) found.
2021-07-02 01:16:25.094929: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88]   (0) Internal: Could not synchronize CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.094935: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 	 [[{{node XRTExecute}}]]
2021-07-02 01:16:25.094939: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 	 [[XRTExecute_G15]]
2021-07-02 01:16:25.094943: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88]   (1) Internal: Could not synchronize CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.094948: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 	 [[{{node XRTExecute}}]]
2021-07-02 01:16:25.094953: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 0 successful operations.
2021-07-02 01:16:25.094958: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88] 0 derived errors ignored.
2021-07-02 01:16:25.094962: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88] Recent warning and error logs:
2021-07-02 01:16:25.094967: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88]   Error blocking host until done in stream destructor: Internal: stream did not block host until done; was already in an error state
2021-07-02 01:16:25.094972: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88]   Error blocking host until done in stream destructor: Internal: stream did not block host until done; was already in an error state
2021-07-02 01:16:25.094980: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88]   failed to enqueue async memcpy from host to device: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered; GPU dst: 0x7f5b63fc0f00; host src: 0x7f5aafddb080; size: 38535168=0x24c0000
2021-07-02 01:16:25.094986: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88]   OP_REQUIRES failed at xrt_execute_op.cc:432 : Internal: Could not synchronize CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-02 01:16:25.094991: E     520 tensorflow/compiler/xla/xla_client/xla_util.cc:88]  
```

**Comment by JackCaoG** [comment] 2021-07-17 03:54
Hey @rwightman I think that is a separate issue, feel free to open an new issue

**Comment by JackCaoG** [comment] 2021-07-17 03:57
I think I know what is going on, amp now has to be manually registered to device in [here](https://github.com/pytorch/pytorch/blob/f89ae9cb8dbd442ee85f39a0bb9572f9be823c21/aten/src/ATen/autocast_mode.cpp#L268) after [this pr](https://github.com/pytorch/pytorch/pull/57386/files#diff-b99d3aff6a9039f8abada80fa8c2647a85d8248fa22b64310a0cc9ca620dad62R275). PyTorch/XLA AMP was just a alias of cuda amp which used to be working because amp doesn't check the device type. I will open an issue on pytorch side and discuss what's the best path forward.

**Comment by JackCaoG** [comment] 2021-07-17 04:11
submitted a pytorch issue https://github.com/pytorch/pytorch/issues/61804

**Comment by JackCaoG** [comment] 2021-07-27 19:00
FYI, the [pytorch side fix](https://github.com/pytorch/pytorch/commit/5408f739f79eb1ab2a6b3ef889e8a86a7bd20bdb) is merged. I verified that amp speed come back to ~1230 img/sec with batch size 256 and amp enabled(with pytorch pr patched). I add the test for `autocast` in https://github.com/pytorch/xla/pull/3057. Remaining item is to run `resnet50` with amp on our gpu test gramwork daily to make sure speed don't regress.

**Comment by JackCaoG** [comment] 2021-07-29 23:09
Close this bug since fix, amp op test, resnet-50 amp test all merged.

**Closed by JackCaoG** 2021-07-29 23:09 UTC
