### ISSUE TITLE
Coexist with Tensorboard

### ISSUE THREAD

**Issue by yaochengji** [pytorch/xla#2973] opened 2021-06-02 22:22 UTC
## To Reproduce

```
import torch_xla.core.xla_model as xm
from torch.utils.tensorboard import SummaryWriter
w = SummaryWriter()
```

## Expected behavior

```
2021-06-02 22:02:28.220893: F tensorflow/core/framework/variant_op_registry.cc:46] Check failed: existing == nullptr (0x158ae28 vs. nullptr)Unary VariantDecodeFn for type_name: tensorflow::data::WrappedDatasetVariant already registered
```

## Environment

 - Reproducible on XLA backend : XLA backend has not been set.
 - torch_xla version: 1.8

**Comment by jysohn23** [comment] 2021-06-03 14:34
I'm not really able to reproduce the issue with the environments we provide on our GCE images:
```
$ conda activate torch-xla-1.8
(torch-xla-1.8) jysohn@repro-tb-crash:~$ python
Python 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch_xla.core.xla_model as xm
>>> from torch.utils.tensorboard import SummaryWriter
>>> w = SummaryWriter()
>>>
```

With:
```
(torch-xla-1.8) jysohn@repro-tb-crash:~$ pip freeze | grep "torch\|tensor"
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.6.0
torch==1.8.0
torch-xla @ https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.8-cp36-cp36m-linux_x86_64.whl
torchvision==0.9.0
(torch-xla-1.8) jysohn@repro-tb-crash:~$ cat /tmp/tb.py
import torch_xla.core.xla_model as xm
from torch.utils.tensorboard import SummaryWriter
w = SummaryWriter()
(torch-xla-1.8) jysohn@repro-tb-crash:~$ python /tmp/tb.py
(torch-xla-1.8) jysohn@repro-tb-crash:~$ echo $?
0

```

Can you report the result of running `pip freeze | grep "torch\|tensor"` on your environment? We should be hitting this path instead using TF stub defined by Tensorboard: https://github.com/tensorflow/tensorboard/blob/abf1759113bae2097e6e5a5482cef86abacbb594/tensorboard/compat/__init__.py#L50 As a temporary workaround could you also try uninstalling TF if you don't need it in the same env?

**Comment by yaochengji** [comment] 2021-06-03 17:50
```
$ pip freeze | grep "torch\|tensor"
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorboardX==2.2
tensorflow==2.4.1
tensorflow-estimator==2.4.0
torch==1.8.1+cu111
torch-xla @ http://tosv.byted.org/obj/turing/fex/torch_xla-1.8-cp37-cp37m-linux_x86_64.whl
torchaudio==0.8.1
torchvision==0.9.1+cu111
```

And I find if I uninstall tensorflow, it could succeed. :)

**Comment by JackCaoG** [comment] 2021-06-04 01:36
I will close this issue since it is resolved. Fell free to reopen if you have further questions.

**Closed by JackCaoG** 2021-06-04 01:36 UTC
