### ISSUE TITLE
pytorch-xla sometimes hangs on thread join in data_parallel.py

### ISSUE THREAD

**Issue by ikirill** [pytorch/xla#824] opened 2019-07-14 01:42 UTC
This is possibly a question, not sure if it's a bug.

I modified `test_train_mnist.py` to run on my own problem, and right before `loss = loss_fn(output, target)` it hangs. When I interrupt it, this is the traceback:
```
^CTraceback (most recent call last):
  [some censored paths]
  File "/anaconda3/envs/pytorch-0.1/lib/python3.6/site-packages/torch_xla_py/data_parallel.py", line 236, in __call__
    thread.join()
  File "/anaconda3/envs/pytorch-0.1/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/anaconda3/envs/pytorch-0.1/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
```

It hangs in some code for dealing with parallel data loading, and I do have a custom dataset that is a straightforward subclass of `torch.utils.data.Dataset`. There is no such problem using pytorch on the CPU on the same machine, and I can run `test_train_mnist.py` with no problems.

**Comment by asuhan** [comment] 2019-07-14 02:54
This might be related to https://github.com/pytorch/xla/issues/821.

**Comment by dlibenzi** [comment] 2019-07-14 05:51
> This is possibly a question, not sure if it's a bug.
> 
> I modified `test_train_mnist.py` to run on my own problem, and right before `loss = loss_fn(output, target)` it hangs. When I interrupt it, this is the traceback:
> 
> ```
> ^CTraceback (most recent call last):
>   [some censored paths]
>   File "/anaconda3/envs/pytorch-0.1/lib/python3.6/site-packages/torch_xla_py/data_parallel.py", line 236, in __call__
>     thread.join()
>   File "/anaconda3/envs/pytorch-0.1/lib/python3.6/threading.py", line 1056, in join
>     self._wait_for_tstate_lock()
>   File "/anaconda3/envs/pytorch-0.1/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
>     elif lock.acquire(block, timeout):
> ```
> 
> It hangs in some code for dealing with parallel data loading, and I do have a custom dataset that is a straightforward subclass of `torch.utils.data.Dataset`. There is no such problem using pytorch on the CPU on the same machine, and I can run `test_train_mnist.py` with no problems.

Getting such stack trace is normal, as that's where the main thread sits.
Are you running on Cloud TPU or local machine XLA CPU?

**Comment by ikirill** [comment] 2019-07-14 10:17
Cloud TPU. 

> Getting such stack trace is normal, as that's where the main thread sits.

Thank you, I didn't understand this.

**Comment by dlibenzi** [comment] 2019-07-14 10:24
Closing this as likely a duplicate of #821 
Please follow discussion on the #821 thread.

**Closed by dlibenzi** 2019-07-14 10:24 UTC
