### ISSUE TITLE
`torch.utils.tensorboard` (or `tensorflow` in general) cannot be imported/used under PT/XLA 1.12 (tpu-vm-pt-1.12)

### ISSUE THREAD

**Issue by ronghanghu** [pytorch/xla#3786] opened 2022-07-27 22:46 UTC
## 🐛 Bug

It seems that the PyTorch/XLA 1.12 release cannot work with `torch.utils.tensorboard` to write tensorboard summary under the `tpu-vm-pt-1.12` TPU runtime -- doing so would lead to a direct crash. Related to this issue,`tensorflow` in general cannot be imported together with `torch_xla` 1.12.

I tried upgrading the tensorboard version (or switching to tb-nightly) or the tensorflow version, but this error persists. I wonder is this because PyTorch/XLA 1.12 is linked against a specific TensorFlow codebase or version that's incompatible with public tensorflow or tensorboard wheels?

## To Reproduce

1. Allocate a v3-8 TPU VM pod from the `tpu-vm-pt-1.12` environment
2. Run the following command on the TPU VM
```bash
python3 -c "
import torch_xla
from torch.utils.tensorboard import SummaryWriter
log_writer = SummaryWriter(log_dir='/tmp')
"
```
which gives a crash
```
2022-07-27 22:22:08.203925: F ./tensorflow/core/tpu/tpu_library_init_fns.inc:100] TpuEmbeddingEngine_CollateMemory not available in this library.
https://symbolize.stripped_domain/r/?trace=7f058078d00b,7f058078d08f,7f044e27a0ea,7f045c9e7046,7f045c9e7616,7f044e53d022,7f0580b4fb99&map= 
*** SIGABRT received by PID 367166 (TID 367166) on cpu 95 from PID 367166; stack trace: ***
PC: @     0x7f058078d00b  (unknown)  raise
    @     0x7f04788ed2f3        992  (unknown)
    @     0x7f058078d090  1427203072  (unknown)
    @     0x7f044e27a0eb        448  tensorflow::tpu::(anonymous namespace)::SetTpuOpsStructFns()
    @     0x7f045c9e7047        128  tensorflow::tpu::InitializeTpuLibrary()
    @     0x7f045c9e7617        592  tensorflow::tpu::FindAndLoadTpuLibrary()
    @     0x7f044e53d023         32  _GLOBAL__sub_I_tpu_api_dlsym_initializer.cc
    @     0x7f0580b4fb9a  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7f058078d00b,7f04788ed2f2,7f058078d08f,7f044e27a0ea,7f045c9e7046,7f045c9e7616,7f044e53d022,7f0580b4fb99&map=5920735bb186a93a82e10840f91bc184:7f04640fa000-7f0478c70fb0 
E0727 22:22:08.288132  367166 coredump_hook.cc:366] RAW: Remote crash data gathering hook invoked.
E0727 22:22:08.288163  367166 coredump_hook.cc:412] RAW: Skipping coredump since rlimit was 0 at process start.
E0727 22:22:08.288171  367166 client.cc:234] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E0727 22:22:08.288180  367166 coredump_hook.cc:473] RAW: Sending fingerprint to remote end.
E0727 22:22:08.288189  367166 coredump_socket.cc:118] RAW: Stat failed errno=2 on socket /var/google/services/logmanagerd/remote_coredump.socket
E0727 22:22:08.288203  367166 coredump_hook.cc:477] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] Missing crash reporting socket. Is the listener running?
E0727 22:22:08.288208  367166 coredump_hook.cc:551] RAW: Discarding core.
E0727 22:22:08.291369  367166 process_state.cc:774] RAW: Raising signal 6 with default behavior
Aborted (core dumped)
```
3. The TensorFlow library also cannot be imported together with PT/XLA 1.12 (under `tpu-vm-pt-1.12` runtime)
```bash
python3 -c "import torch_xla; import tensorflow"
```
which gives the same crash as above
```
2022-07-27 22:30:37.304649: F ./tensorflow/core/tpu/tpu_library_init_fns.inc:100] TpuEmbeddingEngine_CollateMemory not available in this library.
https://symbolize.stripped_domain/r/?trace=7fa51deda00b,7fa51deda08f,7fa3ebf000ea,7fa3fa66d046,7fa3fa66d616,7fa3ec1c3022,7fa51e29cb99&map= 
*** SIGABRT received by PID 368233 (TID 368233) on cpu 95 from PID 368233; stack trace: ***
PC: @     0x7fa51deda00b  (unknown)  raise
    @     0x7fa41603a2f3        992  (unknown)
    @     0x7fa51deda090  (unknown)  (unknown)
    @     0x7fa3ebf000eb        448  tensorflow::tpu::(anonymous namespace)::SetTpuOpsStructFns()
    @     0x7fa3fa66d047        128  tensorflow::tpu::InitializeTpuLibrary()
    @     0x7fa3fa66d617        592  tensorflow::tpu::FindAndLoadTpuLibrary()
    @     0x7fa3ec1c3023         32  _GLOBAL__sub_I_tpu_api_dlsym_initializer.cc
    @     0x7fa51e29cb9a  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7fa51deda00b,7fa41603a2f2,7fa51deda08f,7fa3ebf000ea,7fa3fa66d046,7fa3fa66d616,7fa3ec1c3022,7fa51e29cb99&map=5920735bb186a93a82e10840f91bc184:7fa401847000-7fa4163bdfb0 
E0727 22:30:37.389124  368233 coredump_hook.cc:366] RAW: Remote crash data gathering hook invoked.
E0727 22:30:37.389147  368233 coredump_hook.cc:412] RAW: Skipping coredump since rlimit was 0 at process start.
E0727 22:30:37.389162  368233 client.cc:234] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E0727 22:30:37.389175  368233 coredump_hook.cc:473] RAW: Sending fingerprint to remote end.
E0727 22:30:37.389184  368233 coredump_socket.cc:118] RAW: Stat failed errno=2 on socket /var/google/services/logmanagerd/remote_coredump.socket
E0727 22:30:37.389195  368233 coredump_hook.cc:477] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] Missing crash reporting socket. Is the listener running?
E0727 22:30:37.389199  368233 coredump_hook.cc:551] RAW: Discarding core.
E0727 22:30:37.392171  368233 process_state.cc:774] RAW: Raising signal 6 with default behavior
Aborted (core dumped)
```

## Expected behavior

The following code should not lead to a crash:
```bash
python3 -c "
import torch_xla
from torch.utils.tensorboard import SummaryWriter
log_writer = SummaryWriter(log_dir='/tmp')
"
```
and similarly importing PT/XLA and TensorFlow at the same time should not give a crash
```bash
python3 -c "import torch_xla; import tensorflow"
```

## Environment

 - Reproducible on XLA backend [CPU/TPU]: v3-8 TPU VM with `tpu-vm-pt-1.12` runtime
 - torch_xla version: 1.12

## Additional context

The crash above doesn't happen under PyTorch/XLA 1.10 (`tpu-vm-pt-1.10` runtime) or PyTorch/XLA 1.11 (`tpu-vm-pt-1.11` runtime).

**Comment by JackCaoG** [comment] 2022-07-27 22:56
This is caused by tf try to load the libtpu, but the libtpu for pytorch 1.12 is not compatible with the tf.  set `TPU_LOAD_LIBRARY=0`  before import the tensorboard should stop tf from loading the libtpu. (tensorboard doesn't need libtpu)

**Comment by ronghanghu** [comment] 2022-07-27 23:19
> This is caused by tf try to load the libtpu, but the libtpu for pytorch 1.12 is not compatible with the tf. set `TPU_LOAD_LIBRARY=0` before import the tensorboard should stop tf from loading the libtpu. (tensorboard doesn't need libtpu)

Thanks, @JackCaoG! This `TPU_LOAD_LIBRARY=0` solved my problems above.

**Comment by JackCaoG** [comment] 2022-07-27 23:27
Sounds good! I will close this issue for now. Fell free to reopen if you run into other issues!

**Closed by JackCaoG** 2022-07-27 23:27 UTC

**Comment by yshvrdhn** [comment] 2022-07-29 03:34
while using cloud tpu v38 with pytorch 1.12 prebuilt I am getting the following error : 
```2022-07-29 03:05:56.772945: F ./tensorflow/core/tpu/tpu_library_init_fns.inc:100] TpuEmbeddingEngine_CollateMemory not available in this library.
https://symbolize.stripped_domain/r/?trace=7f7a2695c00b,7f7a2695c08f,7f76efe5f0ea,7f76fe5cc046,7f76fe5cc616,7f76f0122022,7f7a26d1eb99&map= 
*** SIGABRT received by PID 21555 (TID 21555) on cpu 48 from PID 21555; stack trace: ***
PC: @     0x7f7a2695c00b  (unknown)  raise
    @     0x7f791f30b2f3        992  (unknown)
    @     0x7f7a2695c090  (unknown)  (unknown)
    @     0x7f76efe5f0eb        448  tensorflow::tpu::(anonymous namespace)::SetTpuOpsStructFns()
    @     0x7f76fe5cc047        128  tensorflow::tpu::InitializeTpuLibrary()
    @     0x7f76fe5cc617        592  tensorflow::tpu::FindAndLoadTpuLibrary()
    @     0x7f76f0122023         32  _GLOBAL__sub_I_tpu_api_dlsym_initializer.cc
    @     0x7f7a26d1eb9a  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7f7a2695c00b,7f791f30b2f2,7f7a2695c08f,7f76efe5f0ea,7f76fe5cc046,7f76fe5cc616,7f76f0122022,7f7a26d1eb99&map=5920735bb186a93a82e10840f91bc184:7f790ab18000-7f791f68efb0 
E0729 03:05:56.860245   21555 coredump_hook.cc:366] RAW: Remote crash data gathering hook invoked.
E0729 03:05:56.860268   21555 coredump_hook.cc:412] RAW: Skipping coredump since rlimit was 0 at process start.
E0729 03:05:56.860284   21555 client.cc:234] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E0729 03:05:56.860288   21555 coredump_hook.cc:473] RAW: Sending fingerprint to remote end.
E0729 03:05:56.860302   21555 coredump_socket.cc:118] RAW: Stat failed errno=2 on socket /var/google/services/logmanagerd/remote_coredump.socket
E0729 03:05:56.860323   21555 coredump_hook.cc:477] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] Missing crash reporting socket. Is the listener running?
E0729 03:05:56.860331   21555 coredump_hook.cc:551] RAW: Discarding core.
E0729 03:05:57.099368   21555 process_state.cc:774] RAW: Raising signal 6 with default behavior
Aborted (core dumped)```

**Comment by JackCaoG** [comment] 2022-07-29 03:55
This is a libtpu mismatch. Are you import TF for some reason? This is usually an indication that you use TF(for example profiler of TF) and it tried to load libtpu and run into a version mismatch.

**Comment by yshvrdhn** [comment] 2022-07-29 04:07
@JackCaoG yes one of the libraries is using tensorflow. Can I not use tensorflow or should I install another version ? Incase that’s the case can you point me to which tensorflow version to install ?

**Comment by JackCaoG** [comment] 2022-07-29 17:11
@yshvrdhn not an expert on tf but I think if you can uninstall the native tf on the TPUVM and reinstall the tensorflow-cpu, it should install the version that won't load the libtpu.(I am assuming you don't need both tf and pytorch own the TPU hardware at the same time, which is not supported anyway).

**Comment by yshvrdhn** [comment] 2022-07-29 23:07
I see I was able to install tensorflow cpu and resolve the issue.
