### ISSUE TITLE
Missing python 3.9 and 3.11 wheels for torch-xla 2.5.1 on pypi

### ISSUE THREAD

**Issue by jeffhataws** [pytorch/xla#8377] opened 2024-11-13 17:14 UTC
## 🐛 Bug

I see only python 3.10 wheel for torch-xla 2.5.1. https://pypi.org/project/torch-xla/2.5.1/#files

There are 3.9, 3.10, and 3.11 wheels for torch-xla 2.5.0: https://pypi.org/project/torch-xla/2.5.0/#files

## To Reproduce

See  https://pypi.org/project/torch-xla/2.5.1/#files for a list of wheels published

## Expected behavior

Expected python 3.9 and 3.11 wheels

## Environment

 - Reproducible on XLA backend [CPU/TPU/CUDA]:
 - torch_xla version:

**Comment by JackCaoG** [comment] 2024-11-13 18:24
@ManfeiBai Do we know who uploaded the 2.5.1 wheel?

**Comment by ManfeiBai** [comment] 2024-11-13 19:23
Thanks for this issue, have pushed python3.9's and python3.11's torch_xla 2.5.1 wheel to PyPi too: https://pypi.org/project/torch-xla/2.5.1/#files

**Comment by ManfeiBai** [comment] 2024-11-13 19:30
Thanks, since its available on PyPi website now and confirmed locally in python(3.9/3.10/3.11) env, will close this issue

**Closed by ManfeiBai** 2024-11-13 19:30 UTC
