### ISSUE TITLE
Using transposes causes a pair of HLOs being generated for same code

### ISSUE THREAD

**Issue by amithrm** [pytorch/xla#3488] opened 2022-04-11 16:19 UTC
## 🐛 Bug

A pair of HLOs is being generated because of the presence of transpose operator. This is an issue since F.linear uses transposes and we get two HLOs for the same code path across multiple iterations. A simple repro is attached below.
## To Reproduce

1. Use the following code snippet (test.py) :

```
import torch
import torch_xla
from torch import nn
import torch_xla.core.xla_model as xm
import torch.nn.functional as F
from torch.nn.parameter import Parameter
import torch_xla.debug.metrics as met
import os

fileformat = 'hlo'
filename = os.path.splitext(os.path.basename(__file__))[0]+'.'+fileformat
print(filename)

os.environ['XLA_SAVE_TENSORS_FILE'] = filename
os.environ['XLA_SAVE_TENSORS_FMT'] = fileformat

device = xm.xla_device()

weight = torch.randn(10,3).to(device)
xm.mark_step()

for i in range(6):
    input = torch.LongTensor([[1,2,4,5],[4,3,2,9]]).to(device)
    input_parallel = torch.randn(3,10).to(device)
    logits_parallel = torch.matmul(input_parallel, weight)
    x = torch.transpose(weight, 0,1)
    xm.mark_step()

```
2. python test.py3. 
3. The following output is observed in the test_example.hlo which is the trace of the HLOs being executed 

HloModule IrToHlo.7

ENTRY %IrToHlo.7 (p0.1: s64[2,4], p1.2: f32[3,10], p2.3: f32[10,3]) -> (s64[2,4], f32[3,10], f32[3,3], f32[3,10]) {
  %p0.1 = s64[2,4]{1,0} parameter(0)
  %p1.2 = f32[3,10]{1,0} parameter(1)
  %p2.3 = f32[10,3]{1,0} parameter(2)
  %dot.4 = f32[3,3]{1,0} dot(f32[3,10]{1,0} %p1.2, f32[10,3]{1,0} %p2.3), lhs_contracting_dims={1}, rhs_contracting_dims={0}
  %transpose.5 = f32[3,10]{0,1} transpose(f32[10,3]{1,0} %p2.3), dimensions={1,0}
  ROOT %tuple.6 = (s64[2,4]{1,0}, f32[3,10]{1,0}, f32[3,3]{1,0}, f32[3,10]{0,1}) tuple(s64[2,4]{1,0} %p0.1, f32[3,10]{1,0} %p1.2, f32[3,3]{1,0} %dot.4, f32[3,10]{0,1} %transpose.5)
}

HloModule IrToHlo.7

ENTRY %IrToHlo.7 (p0.1: f32[10,3], p1.2: s64[2,4], p2.3: f32[3,10]) -> (f32[10,3], s64[2,4], f32[3,10], f32[3,3], f32[3,10]) {
  %p0.1 = f32[10,3]{1,0} parameter(0)
  %p1.2 = s64[2,4]{1,0} parameter(1)
  %p2.3 = f32[3,10]{1,0} parameter(2)
  %dot.4 = f32[3,3]{1,0} dot(f32[3,10]{1,0} %p2.3, f32[10,3]{1,0} %p0.1), lhs_contracting_dims={1}, rhs_contracting_dims={0}
  %transpose.5 = f32[3,10]{0,1} transpose(f32[10,3]{1,0} %p0.1), dimensions={1,0}
  ROOT %tuple.6 = (f32[10,3]{1,0}, s64[2,4]{1,0}, f32[3,10]{1,0}, f32[3,3]{1,0}, f32[3,10]{0,1}) tuple(f32[10,3]{1,0} %p0.1, s64[2,4]{1,0} %p1.2, f32[3,10]{1,0} %p2.3, f32[3,3]{1,0} %dot.4, f32[3,10]{0,1} %transpose.5)
}

## Expected behavior

As seen from the output above, an extra tensor f32[10,3] gets appended to the output causing a difference in the HLOs. This is a serious problem we see with large HLOs. (i.e HLOs differ with just one extra output parameter).

## Environment

 - Reproducible on XLA backend [CPU/TPU]:
 - torch_xla version:

## Additional context
We feel this is also related to an earlier ticket related to how torch.view is handled by the XLA. An extra tensor is created to handle this operation instead of reusing the underlying memory. 
https://github.com/pytorch/xla/issues/3291

**Comment by JackCaoG** [comment] 2022-04-11 23:20
Can you fix the indentation of 
```
for i in range(6):
input = torch.LongTensor([[1,2,4,5],[4,3,2,9]]).to(device)
input_parallel = torch.randn(3,10).to(device)
logits_parallel = torch.matmul(input_parallel, weight)
x = torch.transpose(weight, 0,1)
xm.mark_step()
```

I am guessing `mark_step` is outside of the for loop?

**Comment by amithrm** [comment] 2022-04-12 00:04
Jack, updated the indentation. Sorry about that..
The mark_step is inside the loop.

**Comment by JackCaoG** [comment] 2022-04-12 19:10
hmm, yea this is weird. Looking at the output ` f32[10,3]{1,0}` was return directly so I am a bit unsure why does it needs to be a output in the first place.. Let me dig into the code a bit more.

**Comment by JackCaoG** [comment] 2022-04-12 19:21
I think issue is somewhere within 
https://github.com/pytorch/xla/blob/4037ca7f2febe0de03edfcd69a871ef5668b488f/torch_xla/csrc/tensor.cpp#L1160

Need to dump a bit more info to root cause it.

**Comment by JackCaoG** [comment] 2022-04-13 00:01
The issue itself doesn't have too much to do with the transpose. it is the fact that
1. You are moving cpu tensor by `torch.randn(10,3).to(device)`, this will evulate randn on CPU and then move to xla device. We usually do `torch.randn(10,3, device=device)` to compute the randn on device instead of host(CPU).

2. `weight` is left out of the for loop but being pulled into the compuation by `transpose`. Its representation keep changing between `xla::Device_data` which is an IR and `xla_data` which is not an IR. They are logically the same thing but different from the tracing perspective(this might be a bug). 

I can look into why `weight`'s representation keep flipping between `xla_data` and `Device_data` node later..

**Comment by JackCaoG** [comment] 2022-04-28 02:33
I think I root cause the issue, this has to be with View construcot did not correctly init its ir_value_ hence https://github.com/pytorch/xla/blob/d9dc45fce19aa3f27bb00f4cd9f4420a58b30da1/torch_xla/csrc/view.h#L152 incorrectly return false and then clear the xla_data. Should be a pretty easy fix.

**Comment by JackCaoG** [comment] 2022-05-02 20:48
@amithrm Fis is merged, I verified that it fixed the issue above. Let me know if you still see the issue with the fix.

**Closed** 2022-05-02 20:47 UTC
