### ISSUE TITLE
Failed to build xla from source 

### ISSUE THREAD

**Issue by Ja1Zhou** [pytorch/xla#2395] opened 2020-08-04 03:24 UTC
## ❓ Questions and Help
I was trying to build pytorch/xla from source and failed. The error happened while building external libraries. 
```Shell
Loading: 0 packages loaded
    currently loading: tensorflow/compiler/xla/xla_client
    Fetching ...e5015c4078010dcea99ea217b7/external/com_google_protobuf; Extracting /home/cambricon/.cache/bazel/_bazel_cambricon/e9c8d4e5015c4078010dcea99ea217b7/external/com_google_protobuf/v3.9.2.zip
ERROR: no such package '@com_google_protobuf//': java.io.IOException: Error extracting /home/cambricon/.cache/bazel/_bazel_cambricon/e9c8d4e5015c4078010dcea99ea217b7/external/com_google_protobuf/v3.9.2.zip to /home/cambricon/.cache/bazel/_bazel_cambricon/e9c8d4e5015c4078010dcea99ea217b7/external/com_google_protobuf: /home/cambricon/.cache/bazel/_bazel_cambricon/e9c8d4e5015c4078010dcea99ea217b7/external/com_google_protobuf/csharp/src/Google.Protobuf.Test/Compatibility (???????)
```
I was building on Ubuntu16.04 with anaconda and was following instructions in CONTRIBUTING.md
I feel that the document is a little bit confusing. I think that the whole process involves building pytorch from source, installing bazelisk and building xla from source
Here is what I did in all.
```Shell
conda create -n xla python=3.7
conda activate xla

git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
git clone --recursive https://github.com/pytorch/xla.git

xla/scripts/apply_patches.sh
pip install lark-parser
conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions future six requests

export CC=clang-8 CXX=clang++-8
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
export DEBUG=1
python setup.py install

go get github.com/bazelbuild/bazelisk
export PATH=$PATH:$(go env GOPATH)/bin

cd xla/
python setup.py install
```
I also wonder if I did everything right to build from source

**Comment by Ja1Zhou** [comment] 2020-08-04 08:26
i managed to start compiling by setting a new output folder with bigger space with
```Shell
export TEST_TMPDIR=/home/cambricon/new/cache
```
Yet I received a new error:
```Shell
tensorflow/compiler/xla/xla_client/computation_client.cc:177:5: error: no viable conversion from 'std::__cxx11::string *' (aka 'basic_string<char> *') to '::tensorflow::internal::CheckOpString'
```
multiple times

**Comment by JackCaoG** [comment] 2020-08-04 18:30
Hi @Ja1Zhou , what's your bazel version? I am using `bazel 3.1.0`.

**Comment by Ja1Zhou** [comment] 2020-08-05 01:09
Hi@JackCaoG , I am also using bazel 3.1.0.

**Comment by JackCaoG** [comment] 2020-08-05 01:27
@Ja1Zhou Are you using the latest pytorch/xla repo? In the line that error was reported I see [this](https://github.com/pytorch/xla/blob/master/third_party/xla_client/computation_client.cc#L177). Can you post the full error log? I have never tried to build on a Ubuntu machine, but your step looks correct to me.

The only thing I do different was to do a 
```
git submodule sync
git submodule update --init --recursive
```
on both pytorch and pytorch/xla dir after I clone them.

**Comment by Ja1Zhou** [comment] 2020-08-05 02:49
@JackCaoG I did do 
```Shell
git submodule sync
git submodule update --init --recursive
```
everytime after I checkout to a tag.
The error above happened when I was on Tag 1.5.0 of pytorch and on Tag 1.5.0 of xla
The full error log is as follows:
```Shell
Building torch_xla version: 0.8
/home/cambricon/new/pytorch/xla/scripts/gen.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if isinstance(default_values, collections.Mapping):
Extracted 1336 functions (0 errors) from /home/cambricon/new/pytorch/xla/scripts/../../torch/csrc/autograd/generated/RegistrationDeclarations.h
331 function overrides in /home/cambricon/new/pytorch/xla/scripts/../torch_xla/csrc/aten_xla_type.h
Generated 1336 wrappers for /home/cambricon/new/pytorch/xla/scripts/../../torch/csrc/autograd/generated/RegistrationDeclarations.h
+ CMD=install
++ dirname /home/cambricon/new/pytorch/xla/build_torch_xla_libs.sh
+ cd /home/cambricon/new/pytorch/xla
+++ pwd
++ printf '%q\n' /home/cambricon/new/pytorch/xla
+ PWD=/home/cambricon/new/pytorch/xla
+ BASE_DIR=/home/cambricon/new/pytorch/xla
+ echo /home/cambricon/new/pytorch/xla
/home/cambricon/new/pytorch/xla
+ THIRD_PARTY_DIR=/home/cambricon/new/pytorch/xla/third_party
+ MODE=opt
+ [[ '' == \1 ]]
+ VERBOSE=
+ [[ '' == \1 ]]
+ XLA_CUDA_CFG=
+ [[ '' == \1 ]]
+ OPTS=(--cxxopt="-std=c++14")
+ [[ clang-8 =~ ^clang ]]
+ OPTS+=(--cxxopt="-Wno-c++11-narrowing")
+ '[' install == clean ']'
+ cp -r -u -p /home/cambricon/new/pytorch/xla/third_party/xla_client /home/cambricon/new/pytorch/xla/third_party/tensorflow/tensorflow/compiler/xla/
+ pushd /home/cambricon/new/pytorch/xla/third_party/tensorflow
~/new/pytorch/xla/third_party/tensorflow ~/new/pytorch/xla
+ bazel build --define framework_shared_object=false -c opt --cxxopt=-std=c++14 --cxxopt=-Wno-c++11-narrowing //tensorflow/compiler/xla/xla_client:libxla_computation_client.so
$TEST_TMPDIR defined: output root default is '/home/cambricon/new/cache' and max_idle_secs default is '15'.
$TEST_TMPDIR defined: output root default is '/home/cambricon/new/cache' and max_idle_secs default is '15'.
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=204
INFO: Reading rc options for 'build' from /home/cambricon/new/pytorch/xla/third_party/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/cambricon/new/pytorch/xla/third_party/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Found applicable config definition build:v2 in file /home/cambricon/new/pytorch/xla/third_party/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /home/cambricon/new/pytorch/xla/third_party/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/cambricon/new/pytorch/xla/third_party/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
WARNING: /home/cambricon/new/pytorch/xla/third_party/tensorflow/tensorflow/core/BUILD:1750:1: in linkstatic attribute of cc_library rule //tensorflow/core:lib_internal: setting 'linkstatic=1' is recommended if there are no object files. Since this rule was created by the macro 'cc_library', the error might have been caused by the macro implementation
WARNING: /home/cambricon/new/pytorch/xla/third_party/tensorflow/tensorflow/core/BUILD:2162:1: in linkstatic attribute of cc_library rule //tensorflow/core:framework_internal: setting 'linkstatic=1' is recommended if there are no object files. Since this rule was created by the macro 'tf_cuda_library', the error might have been caused by the macro implementation
INFO: Analyzed target //tensorflow/compiler/xla/xla_client:libxla_computation_client.so (202 packages loaded, 18897 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /home/cambricon/new/cache/_bazel_cambricon/e9c8d4e5015c4078010dcea99ea217b7/sandbox
ERROR: /home/cambricon/new/pytorch/xla/third_party/tensorflow/tensorflow/compiler/xla/xla_client/BUILD:70:1: C++ compilation of rule '//tensorflow/compiler/xla/xla_client:computation_client_impl' failed (Exit 1)
tensorflow/compiler/xla/xla_client/record_reader.cc:15:3: error: no viable conversion from 'std::__cxx11::string *' (aka 'basic_string<char> *') to '::tensorflow::internal::CheckOpString'
  XLA_CHECK_OK(env->NewRandomAccessFile(path_, &file_));
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./tensorflow/compiler/xla/xla_client/debug_macros.h:11:3: note: expanded from macro 'XLA_CHECK_OK'
  TF_CHECK_OK(c) << "\n" << tensorflow::CurrentStackTrace()
  ^~~~~~~~~~~~~~
./tensorflow/compiler/xla/xla_client/tf_logging.h:76:26: note: expanded from macro 'TF_CHECK_OK'
#define TF_CHECK_OK(val) TF_CHECK_EQ(val, ::tensorflow::Status::OK())
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./tensorflow/compiler/xla/xla_client/tf_logging.h:68:33: note: expanded from macro 'TF_CHECK_EQ'
#define TF_CHECK_EQ(val1, val2) TF_CHECK_OP(Check_EQ, ==, val1, val2)
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./tensorflow/compiler/xla/xla_client/tf_logging.h:65:43: note: expanded from macro 'TF_CHECK_OP'
#define TF_CHECK_OP(name, op, val1, val2) TF_CHECK_OP_LOG(name, op, val1, val2)
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./tensorflow/compiler/xla/xla_client/tf_logging.h:58:48: note: expanded from macro 'TF_CHECK_OP_LOG'
  while (::tensorflow::internal::CheckOpString _result =              \
                                               ^
./tensorflow/core/platform/default/logging.h:299:8: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'std::__cxx11::string *' (aka 'basic_string<char> *') to 'const tensorflow::internal::CheckOpString &' for 1st argument
struct CheckOpString {
       ^
./tensorflow/core/platform/default/logging.h:299:8: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'std::__cxx11::string *' (aka 'basic_string<char> *') to 'tensorflow::internal::CheckOpString &&' for 1st argument
tensorflow/compiler/xla/xla_client/record_reader.cc:29:3: error: no viable conversion from 'std::__cxx11::string *' (aka 'basic_string<char> *') to '::tensorflow::internal::CheckOpString'
  XLA_CHECK_OK(status) << path_ << " offset " << offset_;
  ^~~~~~~~~~~~~~~~~~~~
./tensorflow/compiler/xla/xla_client/debug_macros.h:11:3: note: expanded from macro 'XLA_CHECK_OK'
  TF_CHECK_OK(c) << "\n" << tensorflow::CurrentStackTrace()
  ^~~~~~~~~~~~~~
./tensorflow/compiler/xla/xla_client/tf_logging.h:76:26: note: expanded from macro 'TF_CHECK_OK'
#define TF_CHECK_OK(val) TF_CHECK_EQ(val, ::tensorflow::Status::OK())
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./tensorflow/compiler/xla/xla_client/tf_logging.h:68:33: note: expanded from macro 'TF_CHECK_EQ'
#define TF_CHECK_EQ(val1, val2) TF_CHECK_OP(Check_EQ, ==, val1, val2)
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./tensorflow/compiler/xla/xla_client/tf_logging.h:65:43: note: expanded from macro 'TF_CHECK_OP'
#define TF_CHECK_OP(name, op, val1, val2) TF_CHECK_OP_LOG(name, op, val1, val2)
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./tensorflow/compiler/xla/xla_client/tf_logging.h:58:48: note: expanded from macro 'TF_CHECK_OP_LOG'
  while (::tensorflow::internal::CheckOpString _result =              \
                                               ^
./tensorflow/core/platform/default/logging.h:299:8: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'std::__cxx11::string *' (aka 'basic_string<char> *') to 'const tensorflow::internal::CheckOpString &' for 1st argument
struct CheckOpString {
       ^
./tensorflow/core/platform/default/logging.h:299:8: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'std::__cxx11::string *' (aka 'basic_string<char> *') to 'tensorflow::internal::CheckOpString &&' for 1st argument
2 errors generated.
Target //tensorflow/compiler/xla/xla_client:libxla_computation_client.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 18.216s, Critical Path: 8.87s
INFO: 10 processes: 10 local.
FAILED: Build did NOT complete successfully
Failed to build external libraries: ['/home/cambricon/new/pytorch/xla/build_torch_xla_libs.sh', 'install']
```
I also tried your suggestion, on Tag 1.6.0 of pytorch and on origin/master of xla.
Yet, now I recieve a new error:
```Shell
Building torch_xla version: 1.6
XLA Commit ID: 18fa011c3eba79b93ea38cf5b0946920e45b2053
PyTorch Commit ID: 6aa9959948f42f575f9b505f9625f0f6359b5b74
/home/cambricon/new/pytorch/xla/scripts/gen.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if isinstance(default_values, collections.Mapping):
Extracted 1394 functions (0 errors) from /home/cambricon/new/pytorch/xla/scripts/../../torch/csrc/autograd/generated/RegistrationDeclarations.h
355 function overrides in /home/cambricon/new/pytorch/xla/scripts/../torch_xla/csrc/aten_xla_type.h
Generated 1394 wrappers for /home/cambricon/new/pytorch/xla/scripts/../../torch/csrc/autograd/generated/RegistrationDeclarations.h
AtenXlaType function missed override: Tensor binary_cross_entropy( const Tensor& self, const Tensor& target, const c10::optional<Tensor>& weight, int64_t reduction); // binary_cross_entropy(Tensor,Tensor,c10::optional<Tensor>,int64_t)->Tensor
AtenXlaType function missed override: Tensor binary_cross_entropy_backward( const Tensor& grad_output, const Tensor& self, const Tensor& target, const c10::optional<Tensor>& weight, int64_t reduction); // binary_cross_entropy_backward(Tensor,Tensor,Tensor,c10::optional<Tensor>,int64_t)->Tensor
AtenXlaType function missed override: Tensor binary_cross_entropy_with_logits( const Tensor& self, const Tensor& target, const c10::optional<Tensor>& weight, const c10::optional<Tensor>& pos_weight, int64_t reduction); // binary_cross_entropy_with_logits(Tensor,Tensor,c10::optional<Tensor>,c10::optional<Tensor>,int64_t)->Tensor
AtenXlaType function missed override: Tensor celu(const Tensor& self, Scalar alpha); // celu(Tensor,Scalar)->Tensor
AtenXlaType function missed override: Tensor& celu_(Tensor& self, Scalar alpha); // celu_(Tensor,Scalar)->Tensor
AtenXlaType function missed override: Tensor convolution_overrideable( const Tensor& input, const Tensor& weight, const c10::optional<Tensor>& bias, IntArrayRef stride, IntArrayRef padding, IntArrayRef dilation, bool transposed, IntArrayRef output_padding, int64_t groups); // convolution_overrideable(Tensor,Tensor,c10::optional<Tensor>,IntArrayRef,IntArrayRef,IntArrayRef,bool,IntArrayRef,int64_t)->Tensor
AtenXlaType function missed override: Tensor empty(IntArrayRef size, c10::optional<ScalarType> dtype, c10::optional<Layout> layout, c10::optional<Device> device, c10::optional<bool> pin_memory, c10::optional<MemoryFormat> memory_format); // empty(IntArrayRef,c10::optional<ScalarType>,c10::optional<Layout>,c10::optional<Device>,c10::optional<bool>,c10::optional<MemoryFormat>)->Tensor
AtenXlaType function missed override: Tensor empty_strided(IntArrayRef size, IntArrayRef stride, c10::optional<ScalarType> dtype, c10::optional<Layout> layout, c10::optional<Device> device, c10::optional<bool> pin_memory); // empty_strided(IntArrayRef,IntArrayRef,c10::optional<ScalarType>,c10::optional<Layout>,c10::optional<Device>,c10::optional<bool>)->Tensor
AtenXlaType function missed override: std::tuple<Tensor, Tensor, Tensor> native_batch_norm( const Tensor& input, const c10::optional<Tensor>& weight, const c10::optional<Tensor>& bias, const c10::optional<Tensor>& running_mean, const c10::optional<Tensor>& running_var, bool training, double momentum, double eps); // native_batch_norm(Tensor,c10::optional<Tensor>,c10::optional<Tensor>,c10::optional<Tensor>,c10::optional<Tensor>,bool,double,double)->std::tuple<Tensor,Tensor,Tensor>
AtenXlaType function missed override: std::tuple<Tensor, Tensor, Tensor> native_batch_norm_backward(const Tensor& grad_out, const Tensor& input, const c10::optional<Tensor>& weight, const c10::optional<Tensor>& running_mean, const c10::optional<Tensor>& running_var, const c10::optional<Tensor>& save_mean, const c10::optional<Tensor>& save_invstd, bool train, double eps, std::array<bool, 3> output_mask); // native_batch_norm_backward(Tensor,Tensor,c10::optional<Tensor>,c10::optional<Tensor>,c10::optional<Tensor>,c10::optional<Tensor>,c10::optional<Tensor>,bool,double,std::array<bool,3>)->std::tuple<Tensor,Tensor,Tensor>
AtenXlaType function missed override: std::tuple<Tensor, Tensor, Tensor> native_group_norm( const Tensor& input, const c10::optional<Tensor>& weight, const c10::optional<Tensor>& bias, int64_t N, int64_t C, int64_t HxW, int64_t group, double eps); // native_group_norm(Tensor,c10::optional<Tensor>,c10::optional<Tensor>,int64_t,int64_t,int64_t,int64_t,double)->std::tuple<Tensor,Tensor,Tensor>
AtenXlaType function missed override: std::tuple<Tensor, Tensor, Tensor> native_group_norm_backward(const Tensor& grad_out, const Tensor& input, const Tensor& mean, const Tensor& rstd, const c10::optional<Tensor>& weight, int64_t N, int64_t C, int64_t HxW, int64_t group, std::array<bool, 3> output_mask); // native_group_norm_backward(Tensor,Tensor,Tensor,Tensor,c10::optional<Tensor>,int64_t,int64_t,int64_t,int64_t,std::array<bool,3>)->std::tuple<Tensor,Tensor,Tensor>
AtenXlaType function missed override: std::tuple<Tensor, Tensor, Tensor> native_layer_norm( const Tensor& input, const c10::optional<Tensor>& weight, const c10::optional<Tensor>& bias, int64_t M, int64_t N, double eps); // native_layer_norm(Tensor,c10::optional<Tensor>,c10::optional<Tensor>,int64_t,int64_t,double)->std::tuple<Tensor,Tensor,Tensor>
AtenXlaType function missed override: std::tuple<Tensor, Tensor, Tensor> native_layer_norm_backward(const Tensor& grad_out, const Tensor& input, const Tensor& mean, const Tensor& rstd, const c10::optional<Tensor>& weight, int64_t M, int64_t N, std::array<bool, 3> output_mask); // native_layer_norm_backward(Tensor,Tensor,Tensor,Tensor,c10::optional<Tensor>,int64_t,int64_t,std::array<bool,3>)->std::tuple<Tensor,Tensor,Tensor>
AtenXlaType function missed override: Tensor nll_loss2d_backward(const Tensor& grad_output, const Tensor& self, const Tensor& target, const c10::optional<Tensor>& weight, int64_t reduction, int64_t ignore_index, const Tensor& total_weight); // nll_loss2d_backward(Tensor,Tensor,Tensor,c10::optional<Tensor>,int64_t,int64_t,Tensor)->Tensor
AtenXlaType function missed override: std::tuple<Tensor, Tensor> nll_loss2d_forward( const Tensor& self, const Tensor& target, const c10::optional<Tensor>& weight, int64_t reduction, int64_t ignore_index); // nll_loss2d_forward(Tensor,Tensor,c10::optional<Tensor>,int64_t,int64_t)->std::tuple<Tensor,Tensor>
AtenXlaType function missed override: Tensor nll_loss_backward(const Tensor& grad_output, const Tensor& self, const Tensor& target, const c10::optional<Tensor>& weight, int64_t reduction, int64_t ignore_index, const Tensor& total_weight); // nll_loss_backward(Tensor,Tensor,Tensor,c10::optional<Tensor>,int64_t,int64_t,Tensor)->Tensor
AtenXlaType function missed override: std::tuple<Tensor, Tensor> nll_loss_forward( const Tensor& self, const Tensor& target, const c10::optional<Tensor>& weight, int64_t reduction, int64_t ignore_index); // nll_loss_forward(Tensor,Tensor,c10::optional<Tensor>,int64_t,int64_t)->std::tuple<Tensor,Tensor>
AtenXlaType function missed override: Tensor& resize_(Tensor& self, IntArrayRef size, c10::optional<MemoryFormat> memory_format); // resize_(Tensor,IntArrayRef,c10::optional<MemoryFormat>)->Tensor
Traceback (most recent call last):
  File "/home/cambricon/new/pytorch/xla/scripts/gen.py", line 1143, in <module>
    generate(args)
  File "/home/cambricon/new/pytorch/xla/scripts/gen.py", line 1113, in generate
    assert check_overrides(overrides, overridden)
AssertionError
Failed to generate ATEN bindings: ['/home/cambricon/new/pytorch/xla/scripts/generate_code.sh']
```
Another point is that I am doing this building locally on my own machine, clearly without TPUs. I just wanted to dig into the source codes. Does have no TPUs have something to do with this error?

**Comment by JackCaoG** [comment] 2020-08-05 03:58
You need to use pytorch master with pytorch-xla master. We will release pt/xla 1.6 soon which is compatible with pytorch 1.6. However I would suggest you to try pytorch master with pytorch-xla master, even for  the learning purpose. Our master is almost always has more feature and as stable as our release branches(we have CI running everyday) 😄 .

You do not need a TPU to run or compile pt/xla, you do need to setup the environment variable to use XLA:CPU through. (XLA is our compiler which supports TPU, CPU and GPU). I will share my setup

```
export WITH_XLA=1 NO_CUDA=1 XLA_DEBUG_GC=2 CC=clang-8 CXX=clang++-8 CLANG_FORMAT="clang-format-7"
export COMPILE_PARALLEL=1 DEBUG=1 XLA_IR_DEBUG=1 XLA_HLO_DEBUG=1 TF_CPP_LOG_THREAD_ID=1
export XLA_USE_XRT=1 XRT_DEVICE_MAP="CPU:0;/job:localservice/replica:0/task:0/device:XLA_CPU:0" XRT_WORKERS="localservice:0;grpc://localhost:51011"
```

**Comment by Ja1Zhou** [comment] 2020-08-05 08:00
@JackCaoG Thank you for your solution! I successfully built xla. 
There is one thing that I want to mention. I upgraded my ubuntu to 18.04 before rebuilding everything.
Also, I specified a new bazel output folder with 
```Shell
export TEST_TMPDIR=/home/cambricon/new/newcache
```
because previous build will mess with the current build process.

**Comment by JackCaoG** [comment] 2020-08-05 18:25
Great! I will close this issue for now, feel free to reopen it if you encounter new build issue.

**Closed by JackCaoG** 2020-08-05 18:25 UTC

**Comment by tyoc213** [comment] 2020-08-30 01:46
@JackCaoG tried to build with docker and got this

```
$ xla/scripts/apply_patches.sh
+++ dirname xla/scripts/apply_patches.sh
++ cd xla/scripts
++ pwd -P
+ CDIR=/home/tyoc213/Documentos/github/pytorch/xla/scripts
+ XDIR=/home/tyoc213/Documentos/github/pytorch/xla/scripts/..
+ PTDIR=/home/tyoc213/Documentos/github/pytorch/xla/scripts/../..
+ TORCH_PIN=/home/tyoc213/Documentos/github/pytorch/xla/scripts/../torch_patches/.torch_pin
+ '[' -f /home/tyoc213/Documentos/github/pytorch/xla/scripts/../torch_patches/.torch_pin ']'
+ python /home/tyoc213/Documentos/github/pytorch/xla/scripts/cond_patch.py /home/tyoc213/Documentos/github/pytorch/xla/scripts/../torch_patches /home/tyoc213/Documentos/github/pytorch/xla/scripts/../..
(base) tyoc213@ubu:~/Documentos/github/pytorch$ docker build -t torch-xla -f xla/docker/Dockerfile .
Sending build context to Docker daemon  2.146GB
Step 1/25 : ARG base_image="debian:stretch"
Step 2/25 : FROM "${base_image}"
 ---> 6d935b41319b
Step 3/25 : ARG python_version="3.6"
 ---> Using cache
 ---> 305ddd9d5b5c
Step 4/25 : ARG cloud_build="false"
 ---> Using cache
 ---> a6ff4402d052
Step 5/25 : ARG release_version="nightly"
 ---> Using cache
 ---> a449bb00d2a7
Step 6/25 : ARG cuda="0"
 ---> Using cache
 ---> 405f536d0356
Step 7/25 : ARG cuda_compute="7.0,7.5"
 ---> Using cache
 ---> bda603e010b8
Step 8/25 : ARG cxx_abi="0"
 ---> Using cache
 ---> 38f6eea06876
Step 9/25 : RUN apt-get update
 ---> Using cache
 ---> 37e90ce2ab1c
Step 10/25 : RUN apt-get install -y git sudo python-pip python3-pip
 ---> Using cache
 ---> ded6536c47f6
Step 11/25 : RUN git clone https://github.com/pytorch/pytorch
 ---> Using cache
 ---> 8c378ddf5ffe
Step 12/25 : ENV USE_CUDA "0"
 ---> Using cache
 ---> 00c2e6124f44
Step 13/25 : ENV XLA_CUDA "${cuda}"
 ---> Using cache
 ---> 23fa8b5afbd3
Step 14/25 : ENV TF_CUDA_COMPUTE_CAPABILITIES "${cuda_compute}"
 ---> Using cache
 ---> 1f315bd45b1e
Step 15/25 : ENV CLOUD_BUILD "${cloud_build}"
 ---> Using cache
 ---> e8e8106fb419
Step 16/25 : ENV CXX_ABI "${cxx_abi}"
 ---> Using cache
 ---> 4842f43f6589
Step 17/25 : COPY . /pytorch/xla
 ---> Using cache
 ---> 0221b88e3dde
Step 18/25 : RUN if [ "${cloud_build}" = true ]; then github_branch="${release_version}" &&   if [ "${release_version}" = "nightly" ]; then github_branch="master"; fi &&   cd /pytorch &&   rm -rf xla &&   git clone -b "${github_branch}" --recursive https://github.com/pytorch/xla &&   cd / &&   git clone -b "${github_branch}" --recursive https://github.com/pytorch-tpu/examples tpu-examples; fi
 ---> Using cache
 ---> 53993f64cc37
Step 19/25 : RUN cd /pytorch && bash xla/scripts/build_torch_wheels.sh ${python_version} ${release_version}
 ---> Running in 96dd391117b3
bash: xla/scripts/build_torch_wheels.sh: No such file or directory
The command '/bin/sh -c cd /pytorch && bash xla/scripts/build_torch_wheels.sh ${python_version} ${release_version}' returned a non-zero code: 127

```

Also after that tried to run it with `xla/scripts/build_torch_wheels.sh` I got this [log.zip](https://github.com/pytorch/xla/files/5146191/log.zip)

So in any of the 2 cant compile on my local computer, any hint? something to try?

I also tried with the extra exports that you provided to configure CPU usage.

**Comment by JackCaoG** [comment] 2020-08-30 07:57
@tyoc213 Can you try running the `docker build -t torch-xla -f docker/Dockerfile` inside the xla dir instead of the pytorch dir as the [doc](https://github.com/pytorch/xla/blob/master/CONTRIBUTING.md) suggested? I will submit a pr to fix the doc. The problem is we do a copy in  [here](https://github.com/pytorch/xla/blob/master/docker/Dockerfile#L35) so this command should be run inside xla dir.

as the `build_torch_wheels.sh` the failure came from building the pytorch so I am not very sure what went wrong. The script is still running for me. I will debug a bit if I see the same failure.

**Comment by tyoc213** [comment] 2020-08-31 02:57
@JackCaoG it worked from inside xla directory, maybe later will try from inside xla directory run the build_torch_wheels.sh because from the path that is gived I also executed it on the parent directory (because the patch did run from there OK).

So I got this:

```
Building wheels for collected packages: pyyaml, future
  Building wheel for pyyaml (setup.py) ... done
  Created wheel for pyyaml: filename=PyYAML-5.3.1-cp38-cp38-linux_x86_64.whl size=44619 sha256=a9fdbfce02e652e3c030679dc2dd96c7cc95a03b4dfe33293a84c55ce757b32d
  Stored in directory: /home/tyoc213/.cache/pip/wheels/13/90/db/290ab3a34f2ef0b5a0f89235dc2d40fea83e77de84ed2dc05c
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491059 sha256=6cd96554dc0e39ac9845ab4fdc6a30e0464b4a72cde2431d65b1c87052858ffd
  Stored in directory: /home/tyoc213/.cache/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4
Successfully built pyyaml future
Installing collected packages: pytz, six, python-dateutil, numpy, pandas, plac, idna, urllib3, chardet, requests, murmurhash, cymem, preshed, blis, tqdm, catalogue, srsly, wasabi, thinc, spacy, pillow, future, torch, torchvision, scipy, pyyaml, pyparsing, packaging, fastprogress, kiwisolver, cycler, matplotlib, joblib, threadpoolctl, scikit-learn, dataclasses, fastcore, fastai
Successfully installed blis-0.4.1 catalogue-1.0.0 chardet-3.0.4 cycler-0.10.0 cymem-2.0.3 dataclasses-0.6 fastai-2.0.6 fastcore-1.0.0 fastprogress-1.0.0 future-0.18.2 idna-2.10 joblib-0.16.0 kiwisolver-1.2.0 matplotlib-3.3.1 murmurhash-1.0.2 numpy-1.19.1 packaging-20.4 pandas-1.1.1 pillow-7.2.0 plac-1.1.3 preshed-3.0.2 pyparsing-2.4.7 python-dateutil-2.8.1 pytz-2020.1 pyyaml-5.3.1 requests-2.24.0 scikit-learn-0.23.2 scipy-1.5.2 six-1.15.0 spacy-2.3.2 srsly-1.0.2 thinc-7.4.1 threadpoolctl-2.1.0 torch-1.6.0 torchvision-0.7.0 tqdm-4.48.2 urllib3-1.25.10 wasabi-0.8.0

```
My questions would be

* how I can use this to run for example a simple .py that import and uses to pytorch xla?
* I see that you say that it should be configured to use CPU to run without TPU, in this docker build it is configured as CPU I guess?

Sorry for the lame question, but havent used much docker (as you have seen).

**Comment by JackCaoG** [comment] 2020-08-31 21:44
@tyoc213 Oh you don't need to build docker image if you just want to run pt/xla, we have nightly build everyday. You can pull one of the prebuilt images. Please refer to [this doc](https://github.com/pytorch/xla#-consume-prebuilt-docker-images) for more information. To use XLA:CPU, you can export the environment variable instead of the TPU IP in the instruction. 

If you don't want to use docker to run pt/xla, you can follow the instruction in instruction in [here](https://github.com/pytorch/xla#-consume-prebuilt-docker-images). You will need to compile the tensorflow for the first time, but that should be a one time thing (unless we update the tensorflow version, which doesn't happen very often).
