### ISSUE TITLE
Hang with torch.compile

### ISSUE THREAD

**Issue by sujoysaraswati** [pytorch/xla#5179] opened 2023-06-14 07:52 UTC
## 🐛 Bug

When trying torch.compile on the example below, execution hangs. 

## To Reproduce

Executing the above test case hangs.

1. On Google colab, installed the colab wheel version mentioned from https://github.com/pytorch/xla/tree/master
```
!pip install cloud-tpu-client==0.10 torch==2.0.0 torchvision==0.15.1 https://storage.googleapis.com/tpu-pytorch/wheels/colab/torch_xla-2.0-cp310-cp310-linux_x86_64.whl
```

2. Execute the following test case -
```
import torch
import torch_xla

def fn(a):
  b = a.t()
  b.mul_(1.0)
  return b
  
compiled_fn = torch.compile(fn, backend="torchxla_trace_once")

x = torch.randn([2, 3])
hx = x.to('xla')
hres = compiled_fn(hx)
print(f"result = {hres.cpu()}")
```

Running this is hanging on colab.

## Expected behavior

The code should run to completion.

## Environment

 - Reproducible on XLA backend [CPU/TPU]:
Reproducible on Colab with TPU instance.

 - torch_xla version:
torch version = 2.0.0+cu117
torch_xla version = 2.0.0.dev20230516+colab

**Comment by JackCaoG** [comment] 2023-06-14 22:22
@wonjoolee95 can you take a look when you have some cycle?

**Comment by wonjoolee95** [comment] 2023-06-14 22:28
Sure, will take a look.

**Comment by wonjoolee95** [comment] 2023-06-14 23:44
Ok this is interesting, I can reproduce the behavior on colab as well as a TPUVM v3-8 with 2.0 wheels:
```
wonjoo@t1v-n-c547f49b-w-0:~$ ls /usr/local/lib/python3.8/dist-packages/ | grep libtpu
libtpu
libtpu_nightly-0.1.dev20230213.dist-info
wonjoo@t1v-n-c547f49b-w-0:~$ python
Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> 
>>> # imports pytorch
>>> import torch
>>> 
>>> # imports the torch_xla package
>>> import torch_xla
>>> import torch_xla.core.xla_model as xm
>>> 
>>> 
>>> print(torch.__version__)
2.0.0+cu117
>>> print(torch_xla.__version__)
2.0
>>> 
>>> def fn(a):
...   b = a.t()
...   b.mul_(1.0)
...   return b
... 
>>> compiled_fn = torch.compile(fn, backend="torchxla_trace_once")
>>> x = torch.randn([2, 3])
>>> hx = x.to('xla')

>>> print(hx)
tensor([[-1.6670, -0.1937,  0.7994],
        [-0.0473,  0.7236, -0.0300]], device='xla:1')
>>> hres = compiled_fn(hx) # hangs forever
```
I'll continue to take a look.

**Comment by wonjoolee95** [comment] 2023-06-16 01:06
FWIW, this seems to be related the functionalization, specifically how the in-place `mul_` op behaves. When we disable functionalization, the code succeeds:
```
wonjoo@t1v-n-9eb87547-w-0:~/pytorch/xla$ XLA_DISABLE_FUNCTIONALIZATION=1 python wonjoo-dynamo-hang.py 
2.1.0a0+git96f548a
2.1.0
tensor([[-0.6047, -0.9603],
        [-0.9094,  0.1014],
        [-0.6255, -1.3380]], device='xla:0')
wonjoo@t1v-n-9eb87547-w-0:~/pytorch/xla$ 
```

**Comment by sujoysaraswati** [comment] 2023-06-16 13:37
@wonjoolee95 , do you plan to take it up with PyTorch dynamo functionalization team? We already raised an issue that @karthiknagasub posted above. If you suspect a common issue for you as well, you can add your concerns to https://github.com/pytorch/pytorch/issues/103650.

**Comment by wonjoolee95** [comment] 2024-08-15 23:08
This seems now to be fixed with backend='openxla':
```
Python 3.10.12 (main, Jul  5 2023, 19:22:19) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torch_xla
>>> torch.__version__
'2.4.0a0+git7775fee'
>>> torch_xla.__version__
'2.5.0+gitfcd08bb'
>>> d = torch_xla.device()
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1723763205.644122 2369246 cpu_client.cc:466] TfrtCpuClient created.
>>> d
device(type='xla', index=0)
>>> a = torch.randn(3, 2)
>>> 
>>> a
tensor([[ 0.4619,  0.2878],
        [ 0.2120, -0.0057],
        [ 0.5711, -1.3099]])
>>> a_xla = a.to(d)
>>> 
>>> a_xla
tensor([[ 0.4619,  0.2878],
        [ 0.2120, -0.0057],
        [ 0.5711, -1.3099]], device='xla:0')
>>> def fn(a):
...     b = a.t()
...     b.mul_(1.0)
...     return b
... 
>>> compiled_fn = torch.compile(fn, backend='openxla')
>>> 
>>> x = torch.randn([2, 3])
>>> x_xla = x.to(d)
>>> x_xla
tensor([[ 0.4411,  0.6233,  1.2696],
        [ 0.4086,  1.7539, -0.2510]], device='xla:0')
>>> res_xla = compiled_fn(x_xla)
>>> res_xla
tensor([[ 0.4411,  0.4086],
        [ 0.6233,  1.7539],
        [ 1.2696, -0.2510]], device='xla:0')
>>> 
```
Closing it, feel free to re-open if necessary.

**Closed by wonjoolee95** 2024-08-15 23:08 UTC
