### ISSUE TITLE
[BUG] ScopePusher not available

### ISSUE THREAD

**Issue by cicirori** [pytorch/xla#3631] opened 2022-06-06 09:17 UTC
## 🐛 Bug

I always use the following code snippet to help me do hlo dump graph analysis, which has always worked well on version 1.10.

```
scope = torch_xla._XLAC.profiler.scope_pusher('custom scope name')
# code to scoped
... ...
del scope
```

However, I recently did some tests based on the master version and found that the dumped hlo graphs were missing the scope information. It's needed to switch the namespace of the `ScopePusher` from `torch_xla::` to `torch::lazy::` as well, just like we did with `Node`.

**Comment by JackCaoG** [comment] 2022-06-06 22:15
oh ok.. This is interesting. I thought the primary use case of the `ScopePusher` was we have some composite Node in pytorch/xla layer and we are cleaning up those ops. Do you know why this doesn't work anymore? I didn't look into the code but given that it compiles I was under the impression that it still works.

**Comment by JackCaoG** [comment] 2022-06-06 22:44
Ah I see what's going on, metadata getting code has been moved upstream, I guess this means we should link `torch_xla._XLAC.profiler.scope_pusher` to upstream scope pusher. 

FYI @wonjoolee95 I think this also means all of the scopePusher use case we have in pt/xla is also broken. I think you started clean up those use cases, do you know how many of those is remaining?

**Comment by wonjoolee95** [comment] 2022-06-06 23:07
> Ah I see what's going on, metadata getting code has been moved upstream, I guess this means we should link `torch_xla._XLAC.profiler.scope_pusher` to upstream scope pusher.
> 
> FYI @wonjoolee95 I think this also means all of the scopePusher use case we have in pt/xla is also broken. I think you started clean up those use cases, do you know how many of those is remaining?

Many of these use cases have been removed/lowered, now a quick search through our `ops.cpp` shows 9 more remaining uses of `ScopePusher`. I can handle these, should we consider this a priority since this is causing the regression?

**Comment by JackCaoG** [comment] 2022-06-06 23:11
@wonjoolee95 How much of work would it be to switch to upstream `scopePusher`? If it is just a simple namespace replacement we should do that. It is a regression so we should fix it if possible 😄 .

We should also add a test regarding scopepusher since there are user using it(and I think it is a valid use case).

**Comment by cicirori** [comment] 2022-06-07 01:52
> @wonjoolee95 How much of work would it be to switch to upstream `scopePusher`? If it is just a simple namespace replacement we should do that. It is a regression so we should fix it if possible 😄 .
> 
> We should also add a test regarding scopepusher since there are user using it(and I think it is a valid use case).

A simple namespace replacement should be enough to solve this problem, according to my tests.

**Comment by wonjoolee95** [comment] 2022-06-07 02:44
Thanks for the verification. I'll submit a PR for a namespace replacement soon.

**Comment by wonjoolee95** [comment] 2022-06-10 17:06
This should be fixed, @cicirori could you please verify?

**Comment by miladm** [comment] 2022-06-10 17:29
Thanks for the fix!
Is there a convenient way to add a test for `ScopePusher` functional correctness @wonjoolee95?

**Comment by miladm** [comment] 2022-06-10 17:32
I see we already have tests added. Thanks @wonjoolee95.

**Comment by JackCaoG** [comment] 2022-06-17 23:33
This should be fixed now, closing the bug.

**Closed by JackCaoG** 2022-06-17 23:33 UTC
Labels: bug
